packages:
  - packages/*

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - canvas
  - core-js
  - cwebp-bin
  - cypress
  - esbuild
  - gifsicle
  - jpegtran-bin
  - mongodb-memory-server
  - mozjpeg
  - optipng-bin
  - pngquant-bin
  - sharp
  - vue-demi

patchedDependencies:
  '@vue/apollo-composable@4.2.1': patches/@vue__apollo-composable@4.2.1.patch
