mongo-container:
  image: mongo:5.0.14
  environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=library
  ports:
    - "27017:27017"
  command: mongod
