export enum ErrorCode {
  // Haiku Generation
  HAIKU_GENERATION_FAILED = 'HAIKU_GENERATION_FAILED',
  MAX_ATTEMPTS_EXCEEDED = 'MAX_ATTEMPTS_EXCEEDED',
  INSUFFICIENT_VERSES = 'INSUFFICIENT_VERSES',

  // Cache
  CACHE_READ_FAILED = 'CACHE_READ_FAILED',
  CACHE_WRITE_FAILED = 'CACHE_WRITE_FAILED',

  // Validation
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  INVALID_VERSE = 'INVALID_VERSE',
  INVALID_THEME = 'INVALID_THEME',
  INVALID_FILTER = 'INVALID_FILTER',
  INVALID_SYLLABLE_COUNT = 'INVALID_SYLLABLE_COUNT',
  INVALID_VERSE_COUNT = 'INVALID_VERSE_COUNT',
  INVALID_BOOK_REFERENCE = 'INVALID_BOOK_REFERENCE',
  BLACKLISTED_CHARACTER = 'BLACKLISTED_CHARACTER',

  // Infrastructure - Database
  DATABASE_ERROR = 'DATABASE_ERROR',
  CONNECTION_FAILED = 'CONNECTION_FAILED',
  QUERY_FAILED = 'QUERY_FAILED',

  // Infrastructure - External Services
  EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR',
  OPENAI_ERROR = 'OPENAI_ERROR',
  OPENAI_NOT_CONFIGURED = 'OPENAI_NOT_CONFIGURED',
  OPENAI_RATE_LIMITED = 'OPENAI_RATE_LIMITED',
  DISCORD_ERROR = 'DISCORD_ERROR',

  // Configuration
  CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',
  MISSING_API_KEY = 'MISSING_API_KEY',
  MISSING_ENV_VAR = 'MISSING_ENV_VAR',
}
