/* eslint-disable max-lines -- Data file containing curated book list */
/**
 * PLAIN TEXT source for GutenGuess books.
 * THIS FILE IS GITIGNORED - do not commit!
 *
 * To update books:
 * 1. Edit this file
 * 2. Run: pnpm obfuscate:books
 * 3. Commit the generated gutenguess-books.ts
 */

export interface GutenGuessBook {
  id: number;
  title: string;
  author: string;
  genre: string;
  era: string;
  authorNationality: string;
  emoticons: string;
  notableQuotes: string[];
  publicationYear: number;
  setting: string;
  protagonist: string;
}

export const GUTENGUESS_BOOKS_SOURCE: readonly GutenGuessBook[] = [
  {
    id: 11,
    title: "Alice's Adventures in Wonderland",
    author: 'Lewis Carroll',
    genre: 'Fantasy',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '🐰🎩🍄🃏👸',
    notableQuotes: [
      "We're all mad here.",
      'Curiouser and curiouser!',
      'Off with her head!',
      'Begin at the beginning and go on till you come to the end: then stop.',
      "Who in the world am I? Ah, that's the great puzzle!",
    ],
    publicationYear: 1865,
    setting: 'Wonderland',
    protagonist: 'Young girl',
  },
  {
    id: 16,
    title: 'Peter Pan',
    author: 'J.M. Barrie',
    genre: 'Fantasy',
    era: 'Edwardian',
    authorNationality: 'Scottish',
    emoticons: '🧚✨🏴‍☠️🐊⭐',
    notableQuotes: [
      'To die will be an awfully big adventure.',
      'All children, except one, grow up.',
      'Second star to the right, and straight on till morning.',
      'Dreams do come true, if only we wish hard enough.',
    ],
    publicationYear: 1911,
    setting: 'England',
    protagonist: 'Boy',
  },
  {
    id: 36,
    title: 'The War of the Worlds',
    author: 'H.G. Wells',
    genre: 'Science Fiction',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '👽🔴🌍💥🛸',
    notableQuotes: [
      'No one would have believed in the last years of the nineteenth century...',
      'The chances of anything coming from Mars are a million to one.',
      'Yet across the gulf of space, intellects vast and cool regarded our Earth with envious eyes.',
      'By the toll of a billion deaths man has bought his birthright of the Earth.',
    ],
    publicationYear: 1898,
    setting: 'England',
    protagonist: 'Narrator',
  },
  {
    id: 45,
    title: 'Anne of Green Gables',
    author: 'L.M. Montgomery',
    genre: 'Coming-of-Age',
    era: 'Edwardian',
    authorNationality: 'Canadian',
    emoticons: '👧🏠🌸📚💚',
    notableQuotes: [
      "I'm so glad I live in a world where there are Octobers.",
      'Tomorrow is always fresh with no mistakes in it.',
      'Kindred spirits are not so scarce as I used to think.',
      "It's been my experience that you can nearly always enjoy things if you make up your mind firmly that you will.",
    ],
    publicationYear: 1908,
    setting: 'Canada',
    protagonist: 'Girl',
  },
  {
    id: 55,
    title: 'The Wonderful Wizard of Oz',
    author: 'L. Frank Baum',
    genre: 'Fantasy',
    era: 'Early 20th Century',
    authorNationality: 'American',
    emoticons: '🌪️👠🦁🤖🧙',
    notableQuotes: [
      "There's no place like home.",
      "Toto, I've a feeling we're not in Kansas anymore.",
      'A heart is not judged by how much you love, but by how much you are loved by others.',
      'You have plenty of courage, I am sure. All you need is confidence in yourself.',
    ],
    publicationYear: 1900,
    setting: 'United States',
    protagonist: 'Young girl',
  },
  {
    id: 74,
    title: 'The Adventures of Tom Sawyer',
    author: 'Mark Twain',
    genre: 'Adventure',
    era: 'Gilded Age',
    authorNationality: 'American',
    emoticons: '👦🎣🏝️💀🖌️',
    notableQuotes: [
      'Work consists of whatever a body is obliged to do.',
      'The less there is to justify a traditional custom, the harder it is to get rid of it.',
      'He had discovered a great law of human action: to make a man covet a thing, only make the thing difficult to attain.',
      'Often, the surest way to convey misinformation is to tell the strict truth.',
    ],
    publicationYear: 1876,
    setting: 'United States',
    protagonist: 'Young boy',
  },
  {
    id: 76,
    title: 'Adventures of Huckleberry Finn',
    author: 'Mark Twain',
    genre: 'Adventure',
    era: 'Gilded Age',
    authorNationality: 'American',
    emoticons: '🛶🌊👦🏃🌙',
    notableQuotes: [
      "All right, then, I'll go to hell.",
      'Human beings can be awful cruel to one another.',
      "It warn't no use to try to hide it from Him.",
      "That is just the way with some people. They get down on a thing when they don't know nothing about it.",
    ],
    publicationYear: 1884,
    setting: 'United States',
    protagonist: 'Young boy',
  },
  {
    id: 84,
    title: 'Frankenstein',
    author: 'Mary Shelley',
    genre: 'Gothic Horror',
    era: 'Romantic',
    authorNationality: 'British',
    emoticons: '⚡🧟💀🏔️🔬',
    notableQuotes: [
      'Beware; for I am fearless, and therefore powerful.',
      'Nothing is so painful to the human mind as a great and sudden change.',
      'I ought to be thy Adam, but I am rather the fallen angel.',
      'Life, although it may only be an accumulation of anguish, is dear to me.',
    ],
    publicationYear: 1818,
    setting: 'Europe',
    protagonist: 'Scientist',
  },
  {
    id: 120,
    title: 'Treasure Island',
    author: 'Robert Louis Stevenson',
    genre: 'Adventure',
    era: 'Victorian',
    authorNationality: 'Scottish',
    emoticons: '🏴‍☠️💰🗺️🦜⚓',
    notableQuotes: [
      "Fifteen men on the dead man's chest, yo-ho-ho, and a bottle of rum!",
      "Them that die'll be the lucky ones.",
      'Pieces of eight! Pieces of eight!',
      'Shiver my timbers!',
    ],
    publicationYear: 1883,
    setting: 'Caribbean',
    protagonist: 'Young boy',
  },
  {
    id: 158,
    title: 'Emma',
    author: 'Jane Austen',
    genre: 'Romance',
    era: 'Regency',
    authorNationality: 'British',
    emoticons: '👩💕🏡🎭💐',
    notableQuotes: [
      'I always deserve the best treatment because I never put up with any other.',
      'Silly things do cease to be silly if they are done by sensible people.',
      'One half of the world cannot understand the pleasures of the other.',
      'There are people who the more you do for them, the less they will do for themselves.',
    ],
    publicationYear: 1815,
    setting: 'England',
    protagonist: 'Young woman',
  },
  {
    id: 174,
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    genre: 'Gothic',
    era: 'Victorian',
    authorNationality: 'Irish',
    emoticons: '🖼️👤💀🌹✨',
    notableQuotes: [
      'The only way to get rid of a temptation is to yield to it.',
      'To define is to limit.',
      'I have grown to love secrecy.',
      'Youth is the one thing worth having.',
      'Behind every exquisite thing that existed, there was something tragic.',
    ],
    publicationYear: 1890,
    setting: 'England',
    protagonist: 'Young man',
  },
  {
    id: 244,
    title: 'A Study in Scarlet',
    author: 'Arthur Conan Doyle',
    genre: 'Mystery',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '🔍🎩💉🔴🕵️',
    notableQuotes: [
      'There is nothing new under the sun.',
      'When you have eliminated the impossible, whatever remains must be the truth.',
      "I consider that a man's brain originally is like a little empty attic.",
      'There is nothing more deceptive than an obvious fact.',
    ],
    publicationYear: 1887,
    setting: 'England',
    protagonist: 'Detective',
  },
  {
    id: 345,
    title: 'Dracula',
    author: 'Bram Stoker',
    genre: 'Gothic Horror',
    era: 'Victorian',
    authorNationality: 'Irish',
    emoticons: '🧛🏰🦇🌙💉',
    notableQuotes: [
      'Listen to them, the children of the night. What music they make!',
      'I am Dracula, and I bid you welcome.',
      'The blood is the life!',
      'There are darknesses in life and there are lights.',
      'We learn from failure, not from success!',
    ],
    publicationYear: 1897,
    setting: 'Transylvania',
    protagonist: 'Man',
  },
  {
    id: 730,
    title: 'Oliver Twist',
    author: 'Charles Dickens',
    genre: 'Social Novel',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '👦🍲🏭💔🎩',
    notableQuotes: [
      'Please, sir, I want some more.',
      'There is something about a roused woman.',
      'The law is an ass.',
      'Dignity, and even holiness too, sometimes, are more questions of coat and waistcoat than some people imagine.',
    ],
    publicationYear: 1837,
    setting: 'England',
    protagonist: 'Boy',
  },
  {
    id: 768,
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    genre: 'Gothic Romance',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '🌪️💔🏚️👻❤️',
    notableQuotes: [
      "He's more myself than I am.",
      'Whatever our souls are made of, his and mine are the same.',
      'I have not broken your heart—you have broken it.',
      'Be with me always—take any form—drive me mad!',
      'I cannot live without my life! I cannot live without my soul!',
    ],
    publicationYear: 1847,
    setting: 'England',
    protagonist: 'Woman',
  },
  {
    id: 863,
    title: 'The Mysterious Affair at Styles',
    author: 'Agatha Christie',
    genre: 'Mystery',
    era: 'Interwar',
    authorNationality: 'British',
    emoticons: '☠️🔍💊🏠🧓',
    notableQuotes: [
      "Every murderer is probably somebody's old friend.",
      'The simplest explanation is always the most likely.',
      'The impossible could not have happened, therefore the impossible must be possible.',
      'I am not keeping back facts. Every fact that I know is in your possession.',
    ],
    publicationYear: 1920,
    setting: 'England',
    protagonist: 'Detective',
  },
  {
    id: 1184,
    title: 'The Count of Monte Cristo',
    author: 'Alexandre Dumas',
    genre: 'Adventure',
    era: 'Romantic',
    authorNationality: 'French',
    emoticons: '⛓️💎🗡️🏝️💰',
    notableQuotes: [
      'All human wisdom is summed up in two words: wait and hope.',
      'Life is a storm. One day the sun shines and the next day thunder rolls.',
      'I am not proud, but I am happy; and happiness blinds, I think, more than pride.',
      'Until the day when God will deign to reveal the future to man, all human wisdom is contained in these two words: Wait and Hope.',
    ],
    publicationYear: 1844,
    setting: 'Mediterranean',
    protagonist: 'Prisoner',
  },
  {
    id: 1232,
    title: 'The Prince',
    author: 'Niccolò Machiavelli',
    genre: 'Political Philosophy',
    era: 'Renaissance',
    authorNationality: 'Italian',
    emoticons: '👑🗡️🦊🦁📜',
    notableQuotes: [
      'It is better to be feared than loved.',
      'The ends justify the means.',
      'Men are driven by two principal impulses: love and fear.',
      'Never attempt to win by force what can be won by deception.',
    ],
    publicationYear: 1532,
    setting: 'Italy',
    protagonist: 'Ruler',
  },
  {
    id: 1260,
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    genre: 'Gothic Romance',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '👩📚🏚️🔥❤️',
    notableQuotes: [
      'I am no bird; and no net ensnares me.',
      'Reader, I married him.',
      'I would always rather be happy than dignified.',
      'I care for myself. The more solitary, the more I shall respect myself.',
      'Do you think I am an automaton?—a machine without feelings?',
    ],
    publicationYear: 1847,
    setting: 'England',
    protagonist: 'Governess',
  },
  {
    id: 1342,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    genre: 'Romance',
    era: 'Regency',
    authorNationality: 'British',
    emoticons: '💃🎩💕📝🏛️',
    notableQuotes: [
      'It is a truth universally acknowledged...',
      'You have bewitched me, body and soul.',
      'I could easily forgive his pride, if he had not mortified mine.',
      'My good opinion once lost, is lost forever.',
      "A lady's imagination is very rapid.",
    ],
    publicationYear: 1813,
    setting: 'England',
    protagonist: 'Young woman',
  },
  {
    id: 1399,
    title: 'Anna Karenina',
    author: 'Leo Tolstoy',
    genre: 'Realist Novel',
    era: 'Victorian',
    authorNationality: 'Russian',
    emoticons: '🚂💔👩❄️💃',
    notableQuotes: [
      'All happy families are alike; each unhappy family is unhappy in its own way.',
      "If you look for perfection, you'll never be content.",
      'He stepped down, trying not to look long at her, as if she were the sun.',
      'Respect was invented to cover the empty place where love should be.',
    ],
    publicationYear: 1877,
    setting: 'Russia',
    protagonist: 'Woman',
  },
  {
    id: 1400,
    title: 'Great Expectations',
    author: 'Charles Dickens',
    genre: 'Coming-of-Age',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '👦💰👰🔨⛓️',
    notableQuotes: [
      'I loved her against reason, against promise, against peace.',
      'Suffering has been stronger than all other teaching.',
      'We need never be ashamed of our tears.',
      'In a word, I was too cowardly to do what I knew to be right, as I had been too cowardly to avoid doing what I knew to be wrong.',
    ],
    publicationYear: 1861,
    setting: 'England',
    protagonist: 'Boy',
  },
  {
    id: 1661,
    title: 'The Adventures of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    genre: 'Mystery',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '🔍🎻🧪💨🎩',
    notableQuotes: [
      'Elementary, my dear Watson.',
      'When you have eliminated the impossible, whatever remains must be the truth.',
      'There is nothing more stimulating than a case where everything goes against you.',
      'I never guess. It is a shocking habit—destructive to the logical faculty.',
    ],
    publicationYear: 1892,
    setting: 'England',
    protagonist: 'Detective',
  },
  {
    id: 2600,
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    genre: 'Historical Fiction',
    era: 'Victorian',
    authorNationality: 'Russian',
    emoticons: '⚔️❄️👑💔🇷🇺👨‍👩‍👧',
    notableQuotes: [
      'The strongest of all warriors are these two — Time and Patience.',
      'We can know only that we know nothing.',
      'Nothing is so necessary for a young man as the company of intelligent women.',
      'If everyone fought for their own convictions there would be no war.',
    ],
    publicationYear: 1869,
    setting: 'Russia',
    protagonist: 'Man',
  },
  {
    id: 2701,
    title: 'Moby Dick',
    author: 'Herman Melville',
    genre: 'Adventure',
    era: 'American Renaissance',
    authorNationality: 'American',
    emoticons: '🐋🚢⚓🌊😠',
    notableQuotes: [
      'Call me Ishmael.',
      'It is not down on any map; true places never are.',
      "I know not all that may be coming, but be it what it will, I'll go to it laughing.",
      'Better to sleep with a sober cannibal than a drunken Christian.',
    ],
    publicationYear: 1851,
    setting: 'Pacific Ocean',
    protagonist: 'Sailor',
  },
  {
    id: 2852,
    title: 'The Hound of the Baskervilles',
    author: 'Arthur Conan Doyle',
    genre: 'Mystery',
    era: 'Edwardian',
    authorNationality: 'British',
    emoticons: '🐕🌫️🏚️🔍💀',
    notableQuotes: [
      'Mr. Holmes, they were the footprints of a gigantic hound!',
      'The world is full of obvious things which nobody observes.',
      'Evil indeed is the man who has not one woman to mourn him.',
      'There is nothing more stimulating than a case where everything goes against you.',
    ],
    publicationYear: 1902,
    setting: 'England',
    protagonist: 'Detective',
  },
  {
    id: 8800,
    title: 'The Divine Comedy',
    author: 'Dante Alighieri',
    genre: 'Epic Poetry',
    era: 'Medieval',
    authorNationality: 'Italian',
    emoticons: '🔥👼😈⭐🚶',
    notableQuotes: [
      'Abandon all hope, ye who enter here.',
      'The path to paradise begins in hell.',
      'In the middle of the journey of our life, I came to myself in a dark wood.',
      'There is no greater sorrow than to recall happiness in times of misery.',
      'Love, that moves the sun and the other stars.',
    ],
    publicationYear: 1320,
    setting: 'Afterlife',
    protagonist: 'Pilgrim',
  },
  {
    id: 64317,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    genre: 'Tragedy',
    era: 'Jazz Age',
    authorNationality: 'American',
    emoticons: '🎉💚🥂🚗💔',
    notableQuotes: [
      'So we beat on, boats against the current.',
      "Can't repeat the past? Why of course you can!",
      'In my younger and more vulnerable years my father gave me some advice.',
      "I hope she'll be a fool—a beautiful little fool.",
      'Reserving judgments is a matter of infinite hope.',
    ],
    publicationYear: 1925,
    setting: 'United States',
    protagonist: 'Narrator',
  },
  {
    id: 28054,
    title: 'The Brothers Karamazov',
    author: 'Fyodor Dostoevsky',
    genre: 'Philosophical Fiction',
    era: 'Victorian',
    authorNationality: 'Russian',
    emoticons: '👨‍👨‍👦💔⛪💰😈⚖️',
    notableQuotes: [
      'The soul is healed by being with children.',
      'If God does not exist, everything is permitted.',
      'Above all, do not lie to yourself.',
      'The mystery of human existence lies not in just staying alive, but in finding something to live for.',
    ],
    publicationYear: 1880,
    setting: 'Russia',
    protagonist: 'Young man',
  },
  {
    id: 203,
    title: "Uncle Tom's Cabin",
    author: 'Harriet Beecher Stowe',
    genre: 'Social Novel',
    era: 'Antebellum',
    authorNationality: 'American',
    emoticons: '⛓️🏠💔🙏✊',
    notableQuotes: [
      'The longest way must have its close.',
      'I never thought my heart could hold so much.',
      'So you are the little woman who wrote the book that started this great war.',
      'Any mind that is capable of real sorrow is capable of good.',
    ],
    publicationYear: 1852,
    setting: 'United States',
    protagonist: 'Slave',
  },
  {
    id: 105,
    title: 'Persuasion',
    author: 'Jane Austen',
    genre: 'Romance',
    era: 'Regency',
    authorNationality: 'British',
    emoticons: '💌⚓💕🌊👩',
    notableQuotes: [
      'You pierce my soul. I am half agony, half hope.',
      'There could have been no two hearts so open.',
      'My idea of good company is the company of clever, well-informed people who have a great deal of conversation.',
      'One does not love a place the less for having suffered in it.',
    ],
    publicationYear: 1817,
    setting: 'England',
    protagonist: 'Woman',
  },
  {
    id: 161,
    title: 'Sense and Sensibility',
    author: 'Jane Austen',
    genre: 'Romance',
    era: 'Regency',
    authorNationality: 'British',
    emoticons: '👭💔💕🏡📝',
    notableQuotes: [
      'Know your own happiness.',
      'The more I know of the world, the more I am convinced I shall never see a man whom I can really love.',
      'It is not what we think or feel that makes us who we are. It is what we do.',
      'I will be calm. I will be mistress of myself.',
    ],
    publicationYear: 1811,
    setting: 'England',
    protagonist: 'Woman',
  },
  {
    id: 766,
    title: 'David Copperfield',
    author: 'Charles Dickens',
    genre: 'Bildungsroman',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '👦📖✍️💔🎭',
    notableQuotes: [
      'Whether I shall turn out to be the hero of my own life...',
      'Accidents will occur in the best-regulated families.',
      'Never be mean in anything; never be false; never be cruel.',
      'I only ask to be free. The butterflies are free.',
    ],
    publicationYear: 1850,
    setting: 'England',
    protagonist: 'Boy',
  },
  {
    id: 145,
    title: 'Middlemarch',
    author: 'George Eliot',
    genre: 'Realist Novel',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '👩🔬💔🏘️📚💍',
    notableQuotes: [
      'It is never too late to be what you might have been.',
      'What do we live for, if not to make life less difficult for each other?',
      'People are almost always better than their neighbors think they are.',
      'The growing good of the world is partly dependent on unhistoric acts.',
    ],
    publicationYear: 1871,
    setting: 'England',
    protagonist: 'Young woman',
  },
  {
    id: 6130,
    title: 'The Iliad',
    author: 'Homer',
    genre: 'Epic Poetry',
    era: 'Classical',
    authorNationality: 'Greek',
    emoticons: '⚔️🏛️🐴👑😠',
    notableQuotes: [
      'Sing, O goddess, the anger of Achilles.',
      'There is nothing alive more agonized than man.',
      'Any moment might be our last. Everything is more beautiful because we are doomed.',
      'Hateful to me as the gates of Hades is that man who hides one thing in his heart and speaks another.',
    ],
    publicationYear: -750,
    setting: 'Greece',
    protagonist: 'Warrior',
  },
  {
    id: 996,
    title: 'Don Quixote',
    author: 'Miguel de Cervantes',
    genre: 'Satire',
    era: 'Spanish Golden Age',
    authorNationality: 'Spanish',
    emoticons: '🐴🏰🌾💫🛡️',
    notableQuotes: [
      'Tilting at windmills.',
      'The truth may be stretched thin, but it never breaks.',
      'Too much sanity may be madness — and maddest of all: to see life as it is, and not as it should be!',
      'When life itself seems lunatic, who knows where madness lies?',
    ],
    publicationYear: 1605,
    setting: 'Spain',
    protagonist: 'Old man',
  },
  {
    id: 1497,
    title: 'The Republic',
    author: 'Plato',
    genre: 'Philosophy',
    era: 'Classical',
    authorNationality: 'Greek',
    emoticons: '🏛️💭⚖️🔥👁️⛓️',
    notableQuotes: [
      'The myth of the cave.',
      'Justice in the life and conduct of the State is possible only as first it resides in the hearts of the citizens.',
      'The measure of a man is what he does with power.',
      'Be kind, for everyone you meet is fighting a hard battle.',
    ],
    publicationYear: -375,
    setting: 'Greece',
    protagonist: 'Philosopher',
  },
  {
    id: 69087,
    title: 'The Murder of Roger Ackroyd',
    author: 'Agatha Christie',
    genre: 'Mystery',
    era: 'Interwar',
    authorNationality: 'British',
    emoticons: '🔪🕵️📓🏠😱',
    notableQuotes: [
      'The truth, however ugly in itself, is always curious and beautiful to seekers after it.',
      'Very few of us are what we seem.',
      'The simplest explanation is always the most likely.',
      'I am a man who puts an immense value on the personal touch.',
    ],
    publicationYear: 1926,
    setting: 'England',
    protagonist: 'Detective',
  },
  {
    id: 21,
    title: "Aesop's Fables",
    author: 'Aesop',
    genre: 'Fables',
    era: 'Classical',
    authorNationality: 'Greek',
    emoticons: '🦊🐢🦁🐜📖',
    notableQuotes: [
      'Slow and steady wins the race.',
      'A bird in the hand is worth two in the bush.',
      'No act of kindness, no matter how small, is ever wasted.',
      "Beware the wolf in sheep's clothing.",
    ],
    publicationYear: -600,
    setting: 'Greece',
    protagonist: 'Animal',
  },
  {
    id: 1998,
    title: 'Thus Spoke Zarathustra',
    author: 'Friedrich Nietzsche',
    genre: 'Philosophy',
    era: 'Victorian',
    authorNationality: 'German',
    emoticons: '🏔️🦅💫🔥🧙🐍',
    notableQuotes: [
      'God is dead.',
      'What does not kill me makes me stronger.',
      'He who has a why to live for can bear almost any how.',
      'You must have chaos within you to give birth to a dancing star.',
    ],
    publicationYear: 1883,
    setting: 'Allegorical',
    protagonist: 'Prophet',
  },
  {
    id: 2641,
    title: 'A Room with a View',
    author: 'E.M. Forster',
    genre: 'Romance',
    era: 'Edwardian',
    authorNationality: 'British',
    emoticons: '🏠🌅💕🇮🇹🪟',
    notableQuotes: [
      'We cast a shadow on something wherever we stand.',
      'Life is easy to chronicle, but bewildering to practice.',
      'You can transmit vitality, you cannot transmit love of life.',
      'It is so difficult—at least, I find it difficult—to understand people who speak the truth.',
    ],
    publicationYear: 1908,
    setting: 'Italy',
    protagonist: 'Young woman',
  },
  {
    id: 408,
    title: 'The Souls of Black Folk',
    author: 'W.E.B. Du Bois',
    genre: 'Essays',
    era: 'Early 20th Century',
    authorNationality: 'American',
    emoticons: '✊🎵📚🌿💭',
    notableQuotes: [
      'The problem of the twentieth century is the problem of the color line.',
      'Either America will destroy ignorance or ignorance will destroy America.',
      'To be a poor man is hard, but to be a poor race in a land of dollars is the very bottom of hardships.',
      'The cost of liberty is less than the price of repression.',
    ],
    publicationYear: 1903,
    setting: 'United States',
    protagonist: 'Writer',
  },
  {
    id: 16389,
    title: 'The Enchanted April',
    author: 'Elizabeth von Arnim',
    genre: 'Romance',
    era: 'Interwar',
    authorNationality: 'British',
    emoticons: '🌸🏰🇮🇹☀️💐',
    notableQuotes: [
      'The secret of life is in appreciating its blessings.',
      'Every moment of this April will be alive.',
      'If you will be happy, nobody can stop you.',
      'One has to live in the sunshine while one can.',
    ],
    publicationYear: 1922,
    setting: 'Italy',
    protagonist: 'Woman',
  },
  {
    id: 8492,
    title: 'The King in Yellow',
    author: 'Robert W. Chambers',
    genre: 'Horror',
    era: 'Victorian',
    authorNationality: 'American',
    emoticons: '👑💛🎭😱📖',
    notableQuotes: [
      'Have you found the Yellow Sign?',
      'The King in Yellow must not be described.',
      'Along the shore the cloud waves break, the twin suns sink beneath the lake.',
      'Strange is the night where black stars rise.',
    ],
    publicationYear: 1895,
    setting: 'United States',
    protagonist: 'Narrator',
  },
  {
    id: 67979,
    title: 'The Blue Castle',
    author: 'L.M. Montgomery',
    genre: 'Romance',
    era: 'Interwar',
    authorNationality: 'Canadian',
    emoticons: '🏰💙💕🌲✨',
    notableQuotes: [
      "I'll be wicked and frivolous to the end of my days.",
      'Fear is the original sin.',
      'If you can sit in silence with a person for half an hour and yet be entirely comfortable, you and that person can be friends.',
      'I want to do something splendid.',
    ],
    publicationYear: 1926,
    setting: 'Canada',
    protagonist: 'Woman',
  },
  {
    id: 70875,
    title: 'Arrowsmith',
    author: 'Sinclair Lewis',
    genre: 'Social Novel',
    era: 'Jazz Age',
    authorNationality: 'American',
    emoticons: '🔬💉🏥📚🧪',
    notableQuotes: [
      'The purpose of a university is not to produce conformists.',
      'Science is lonely work.',
      'He was a seeker of truths and not of comforts.',
      'The only way to get work is to work.',
    ],
    publicationYear: 1925,
    setting: 'United States',
    protagonist: 'Doctor',
  },
  {
    id: 394,
    title: 'Cranford',
    author: 'Elizabeth Gaskell',
    genre: 'Social Novel',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '👵🏡🍵👗💬',
    notableQuotes: [
      'Cranford is in possession of the Amazons.',
      'A man is so in the way in the house.',
      'What does it signify how we dress here at Cranford?',
      'Economy was always elegant.',
    ],
    publicationYear: 1851,
    setting: 'England',
    protagonist: 'Narrator',
  },
  {
    id: 986,
    title: 'Master and Man',
    author: 'Leo Tolstoy',
    genre: 'Novella',
    era: 'Victorian',
    authorNationality: 'Russian',
    emoticons: '❄️🐴💰👨‍🌾🌨️',
    notableQuotes: [
      'What is the meaning of my life?',
      'We can only know that we know nothing.',
      'The snow was falling from the sky with great force.',
      'He felt in his pockets for a match.',
    ],
    publicationYear: 1895,
    setting: 'Russia',
    protagonist: 'Merchant',
  },
  {
    id: 3600,
    title: 'The Essays of Montaigne',
    author: 'Michel de Montaigne',
    genre: 'Essays',
    era: 'Renaissance',
    authorNationality: 'French',
    emoticons: '📜✍️💭🏰🍷🪞',
    notableQuotes: [
      'Que sais-je? (What do I know?)',
      'The only thing certain is that nothing is certain.',
      'I quote others only in order the better to express myself.',
      "The greater part of the world's troubles are due to questions of grammar.",
    ],
    publicationYear: 1580,
    setting: 'France',
    protagonist: 'Writer',
  },
  {
    id: 224,
    title: 'A Pair of Blue Eyes',
    author: 'Thomas Hardy',
    genre: 'Romance',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '👀💙💔🏴󠁧󠁢󠁥󠁮󠁧󠁿🌊',
    notableQuotes: [
      'A woman who loves ever so little is often greater than the greatest man.',
      'Time changes everything except something within us which is always surprised by change.',
      'The sky was clear—remarkably clear—and the twinkling of all the stars seemed to be but throbs of one body.',
      'Youth is foolish; and so is love.',
    ],
    publicationYear: 1873,
    setting: 'England',
    protagonist: 'Young woman',
  },
  {
    id: 1259,
    title: 'Twenty Years After',
    author: 'Alexandre Dumas',
    genre: 'Adventure',
    era: 'Romantic',
    authorNationality: 'French',
    emoticons: '⚔️🤝👑🏇🗡️',
    notableQuotes: [
      'All for one, one for all.',
      'There is neither happiness nor misery in the world; there is only the comparison of one state with another.',
      'True friends are hard to find, harder to leave, and impossible to forget.',
      'A brave man runs as great a risk in becoming a coward as a coward in becoming a brave man.',
    ],
    publicationYear: 1845,
    setting: 'France',
    protagonist: 'Swordsman',
  },
  {
    id: 3207,
    title: 'Leviathan',
    author: 'Thomas Hobbes',
    genre: 'Political Philosophy',
    era: 'Early Modern',
    authorNationality: 'British',
    emoticons: '👑📜⚖️🐉🏛️😨',
    notableQuotes: [
      'Life is nasty, brutish, and short.',
      'The condition of man is a condition of war of everyone against everyone.',
      'Hell is truth seen too late.',
      'Covenants, without the sword, are but words.',
    ],
    publicationYear: 1651,
    setting: 'Theoretical',
    protagonist: 'Ruler',
  },
  {
    id: 3296,
    title: 'Confessions',
    author: 'Saint Augustine',
    genre: 'Autobiography',
    era: 'Classical',
    authorNationality: 'Roman',
    emoticons: '🙏📖💡✝️👤🍐',
    notableQuotes: [
      'Our hearts are restless until they rest in You.',
      'Grant me chastity and continence, but not yet.',
      'The world is a book, and those who do not travel read only one page.',
      'Men go abroad to wonder at the heights of mountains, and they pass by themselves without wondering.',
    ],
    publicationYear: 397,
    setting: 'North Africa',
    protagonist: 'Saint',
  },
  {
    id: 3300,
    title: 'The Wealth of Nations',
    author: 'Adam Smith',
    genre: 'Economics',
    era: 'Enlightenment',
    authorNationality: 'Scottish',
    emoticons: '💰📈🏭🤝📊✋',
    notableQuotes: [
      'It is not from the benevolence of the butcher that we expect our dinner.',
      'The invisible hand of the market.',
      'No society can surely be flourishing and happy, of which the far greater part of the members are poor and miserable.',
      'Labour was the first price, the original purchase-money that was paid for all things.',
    ],
    publicationYear: 1776,
    setting: 'Britain',
    protagonist: 'Economist',
  },
  {
    id: 5827,
    title: 'The Problems of Philosophy',
    author: 'Bertrand Russell',
    genre: 'Philosophy',
    era: 'Edwardian',
    authorNationality: 'British',
    emoticons: '🤔💭📚🧠❓🪑',
    notableQuotes: [
      'The value of philosophy is in its very uncertainty.',
      'Philosophy is to be studied not for definite answers but rather for the questions themselves.',
      'There is much pleasure to be gained from useless knowledge.',
      'The observer, when he seems to himself to be observing a stone, is really observing the effects of the stone upon himself.',
    ],
    publicationYear: 1912,
    setting: 'Theoretical',
    protagonist: 'Philosopher',
  },
  {
    id: 6593,
    title: 'The History of Tom Jones, a Foundling',
    author: 'Henry Fielding',
    genre: 'Picaresque',
    era: 'Georgian',
    authorNationality: 'British',
    emoticons: '👶🏠💕🎭🍺',
    notableQuotes: [
      'It is much easier to make good men wise than to make bad men good.',
      'Love and scandal are the best sweeteners of tea.',
      'A single bad act no more constitutes a villain in life than a single bad part on the stage.',
      'Guilt has very quick ears to an accusation.',
    ],
    publicationYear: 1749,
    setting: 'England',
    protagonist: 'Orphan',
  },
  {
    id: 6761,
    title: 'The Adventures of Ferdinand Count Fathom',
    author: 'Tobias Smollett',
    genre: 'Satire',
    era: 'Georgian',
    authorNationality: 'Scottish',
    emoticons: '🎭🗡️💰😈🎪',
    notableQuotes: [
      'A knave is a knave in any country.',
      'Nothing is more deceitful than the appearance of humility.',
      'Vice should always be exposed to contempt, but the virtuous may claim our applause.',
      'The world is a vast comedy of errors.',
    ],
    publicationYear: 1753,
    setting: 'Europe',
    protagonist: 'Man',
  },
  {
    id: 11030,
    title: 'Incidents in the Life of a Slave Girl',
    author: 'Harriet Jacobs',
    genre: 'Autobiography',
    era: 'Antebellum',
    authorNationality: 'American',
    emoticons: '⛓️🏃‍♀️🙏📖✊',
    notableQuotes: [
      'Slavery is terrible for men; but it is far more terrible for women.',
      'I was born a slave; but I never knew it till six years of happy childhood had passed away.',
      'There is no shadow of law to protect her from insult, from violence, or even from death.',
      'My master began to whisper foul words in my ear.',
    ],
    publicationYear: 1861,
    setting: 'United States',
    protagonist: 'Slave',
  },
  {
    id: 22381,
    title: 'Myths and Legends of Ancient Greece and Rome',
    author: 'E.M. Berens',
    genre: 'Mythology',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '⚡🏛️🐉🦅🌿',
    notableQuotes: [
      'The gods were supposed to resemble mortals, whom they far surpassed in beauty.',
      'In the beginning there was Chaos.',
      'The gods of Olympus were believed to dwell on the summit of Mount Olympus.',
      'Zeus was the supreme ruler of gods and men.',
    ],
    publicationYear: 1880,
    setting: 'Greece',
    protagonist: 'Hero',
  },
  {
    id: 24869,
    title: 'The Ramayana',
    author: 'Valmiki',
    genre: 'Epic Poetry',
    era: 'Classical',
    authorNationality: 'Indian',
    emoticons: '🏹👑🐒🌺🔥',
    notableQuotes: [
      'Dharma is the basis of the universe.',
      'Truth is the highest virtue.',
      'A person is born alone and dies alone; and he experiences the good and bad consequences of his karma alone.',
      'One should perform his deeds for the benefit of mankind.',
    ],
    publicationYear: -400,
    setting: 'India',
    protagonist: 'Prince',
  },
  {
    id: 27827,
    title: 'The Kama Sutra',
    author: 'Vatsyayana',
    genre: 'Philosophy',
    era: 'Classical',
    authorNationality: 'Indian',
    emoticons: '💕🌸📜🕉️🎭',
    notableQuotes: [
      'Pleasure is as necessary for existence as food.',
      'A man should learn the arts and sciences from the very beginning.',
      'Love grows by giving.',
      'A wise man should marry a girl who is neither too fair nor too dark.',
    ],
    publicationYear: 300,
    setting: 'India',
    protagonist: 'Reader',
  },
  {
    id: 36034,
    title: 'White Nights',
    author: 'Fyodor Dostoevsky',
    genre: 'Novella',
    era: 'Victorian',
    authorNationality: 'Russian',
    emoticons: '🌙💔🚶😢🌃',
    notableQuotes: [
      'My God, a whole minute of bliss! Is that too little for a whole lifetime?',
      'I am a dreamer.',
      'At certain moments I feel so much happiness that it frightens me.',
      'I used to spend whole days in my room, and could not bring myself to go out.',
    ],
    publicationYear: 1848,
    setting: 'Russia',
    protagonist: 'Dreamer',
  },
  {
    id: 55264,
    title: 'On Growth and Form',
    author: "D'Arcy Wentworth Thompson",
    genre: 'Science',
    era: 'Edwardian',
    authorNationality: 'Scottish',
    emoticons: '🐚🔬📐🌀🦋',
    notableQuotes: [
      'The form of an object is a diagram of forces.',
      'Cell and tissue, shell and bone, leaf and flower, are so many portions of matter.',
      'Mathematics is the study of all possible worlds.',
      'The harmony of the world is made manifest in Form and Number.',
    ],
    publicationYear: 1917,
    setting: 'Theoretical',
    protagonist: 'Scientist',
  },
  {
    id: 70114,
    title: 'The Big Four',
    author: 'Agatha Christie',
    genre: 'Mystery',
    era: 'Interwar',
    authorNationality: 'British',
    emoticons: '🔍🎩4️⃣😈🌍',
    notableQuotes: [
      'I am not one to rely upon the expert opinion.',
      'The little grey cells, they still function.',
      'There are four of them, and between them they rule the world.',
      'Method, order, and exactness. These are the things which matter.',
    ],
    publicationYear: 1927,
    setting: 'Worldwide',
    protagonist: 'Detective',
  },
  {
    id: 4085,
    title: 'The Adventures of Roderick Random',
    author: 'Tobias Smollett',
    genre: 'Picaresque',
    era: 'Georgian',
    authorNationality: 'Scottish',
    emoticons: '⚓🗡️💔🎭🌊',
    notableQuotes: [
      'Facts are stubborn things.',
      'Misfortunes one can endure—they come from outside.',
      'I left England, uncertain of my fate.',
      'Fortune is a fickle goddess.',
    ],
    publicationYear: 1748,
    setting: 'Europe',
    protagonist: 'Sailor',
  },
  {
    id: 70882,
    title: 'The Clue of the New Pin',
    author: 'Edgar Wallace',
    genre: 'Mystery',
    era: 'Interwar',
    authorNationality: 'British',
    emoticons: '📍🔍💀🏠🔐',
    notableQuotes: [
      'The cleverest criminal leaves clues.',
      'Murder will out.',
      'Every lock has a key, and every mystery has a solution.',
      'The truth has a way of coming to light.',
    ],
    publicationYear: 1923,
    setting: 'England',
    protagonist: 'Journalist',
  },
  {
    id: 72133,
    title: 'The Octopus',
    author: 'Frank Norris',
    genre: 'Naturalism',
    era: 'Progressive Era',
    authorNationality: 'American',
    emoticons: '🐙🌾🚂💰⚔️',
    notableQuotes: [
      'The wheat is growing.',
      'Force only can succeed in the world.',
      'The great iron monster with its single eye, cyclopean, red.',
      'Men were nothing, death was nothing, life was nothing.',
    ],
    publicationYear: 1901,
    setting: 'United States',
    protagonist: 'Farmer',
  },
  {
    id: 70883,
    title: "Doctor Hathern's Daughters",
    author: 'Mrs. H.B. Paull',
    genre: 'Fiction',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '👨‍⚕️👩‍👧‍👧🏠💕📖',
    notableQuotes: [
      'A good family is a blessing beyond measure.',
      'The heart knows what the mind often forgets.',
      'Kindness is a language which the deaf can hear and the blind can see.',
      'Every home has its story to tell.',
    ],
    publicationYear: 1895,
    setting: 'English village',
    protagonist: 'Woman',
  },
  {
    id: 3306,
    title: 'At Suvla Bay',
    author: 'John Hargrave',
    genre: 'War Memoir',
    era: 'WWI',
    authorNationality: 'British',
    emoticons: '⚔️🏥🌅💀🎖️',
    notableQuotes: [
      'War is not a picnic.',
      'The stretcher-bearers worked without rest.',
      'We had come through hell together.',
      'Every man did his duty that day.',
    ],
    publicationYear: 1916,
    setting: 'Turkey',
    protagonist: 'Soldier',
  },
  {
    id: 70236,
    title: 'The Secret of the Old Mill',
    author: 'Franklin W. Dixon',
    genre: 'Mystery',
    era: 'Interwar',
    authorNationality: 'American',
    emoticons: '🏭🔍👦💵🕵️',
    notableQuotes: [
      'Every mystery has a solution.',
      'The Hardy Boys never give up.',
      'Clues can be found in the most unexpected places.',
      'Teamwork makes the dream work.',
    ],
    publicationYear: 1927,
    setting: 'United States',
    protagonist: 'Young man',
  },
  {
    id: 70302,
    title: 'Education and the Good Life',
    author: 'Bertrand Russell',
    genre: 'Philosophy',
    era: 'Interwar',
    authorNationality: 'British',
    emoticons: '📚👶🎓💭🌍',
    notableQuotes: [
      'The good life is one inspired by love and guided by knowledge.',
      'Fear is the main source of superstition.',
      'The fundamental defect of fathers is that they want their children to be a credit to them.',
      'Education should aim at giving children the ability to think, not to accept beliefs.',
    ],
    publicationYear: 1926,
    setting: 'Theoretical',
    protagonist: 'Philosopher',
  },
  {
    id: 70471,
    title: 'Kabuki',
    author: 'Zoé Kincaid',
    genre: 'Cultural Study',
    era: 'Interwar',
    authorNationality: 'American',
    emoticons: '🎭🇯🇵👘🎶💃',
    notableQuotes: [
      'Kabuki is the theater of the people.',
      'Every gesture carries centuries of meaning.',
      'The art is in the details.',
      'Tradition and innovation dance together on stage.',
    ],
    publicationYear: 1925,
    setting: 'Japan',
    protagonist: 'Actor',
  },
  {
    id: 70525,
    title: 'Sahara',
    author: 'E.D. Morel',
    genre: 'Travel',
    era: 'Edwardian',
    authorNationality: 'British',
    emoticons: '🏜️🐪☀️🌅🧭',
    notableQuotes: [
      'The desert has its own beauty.',
      'Silence is the language of the Sahara.',
      'The sands tell a story older than time.',
      'Under the endless sky, man finds his insignificance.',
    ],
    publicationYear: 1912,
    setting: 'North Africa',
    protagonist: 'Traveler',
  },
  {
    id: 71449,
    title: 'Meg of the Heather',
    author: 'Annie S. Swan',
    genre: 'Romance',
    era: 'Edwardian',
    authorNationality: 'Scottish',
    emoticons: '💜🏴󠁧󠁢󠁳󠁣󠁴󠁿💕🌸👩',
    notableQuotes: [
      'The heather blooms in the heart.',
      'Love finds a way through the moors.',
      'Scotland sings in my soul.',
      'The wild beauty of the Highlands cannot be tamed.',
    ],
    publicationYear: 1908,
    setting: 'Scottish Highlands',
    protagonist: 'Woman',
  },
  {
    id: 71450,
    title: "My Heart's in the Highlands",
    author: 'Annie S. Swan',
    genre: 'Romance',
    era: 'Edwardian',
    authorNationality: 'Scottish',
    emoticons: '❤️🏔️🏴󠁧󠁢󠁳󠁣󠁴󠁿🎵💕',
    notableQuotes: [
      'Home is where the heart beats strongest.',
      'The mountains call to those who love them.',
      'A Scottish heart never forgets its homeland.',
      'In the Highlands, dreams take flight.',
    ],
    publicationYear: 1910,
    setting: 'Scottish Highlands',
    protagonist: 'Man',
  },
  {
    id: 72123,
    title: 'The Arctic World',
    author: 'Charles H. Raye',
    genre: 'Science',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '❄️🐻‍❄️🌊🧊🛷',
    notableQuotes: [
      'The Arctic holds mysteries yet to be discovered.',
      'Ice and snow shape all life here.',
      'In this frozen world, survival is the only law.',
      'The aurora dances across the endless night.',
    ],
    publicationYear: 1876,
    setting: 'Arctic regions',
    protagonist: 'Explorer',
  },
  {
    id: 72132,
    title: "Daddy Joe's Fiddle",
    author: 'Hattie Arnold Clark',
    genre: 'Fiction',
    era: 'Victorian',
    authorNationality: 'American',
    emoticons: '🎻👴👶🎵❤️',
    notableQuotes: [
      'Music speaks when words fail.',
      'The old fiddle tells stories of generations past.',
      'Every tune carries a memory.',
      'Through melody, love is remembered.',
    ],
    publicationYear: 1890,
    setting: 'Rural America',
    protagonist: 'Old man',
  },
  {
    id: 73340,
    title: 'Worthy of His Name',
    author: 'Jennie Chappell',
    genre: 'Religious Fiction',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '✝️📖🙏💒👤',
    notableQuotes: [
      'To be worthy is to serve others.',
      'Faith guides the humble heart.',
      'In service we find our purpose.',
      'The measure of worth is in our deeds.',
    ],
    publicationYear: 1894,
    setting: 'English village',
    protagonist: 'Man',
  },
  {
    id: 70473,
    title: 'Dorian',
    author: 'Nephi Anderson',
    genre: 'Religious Fiction',
    era: 'Progressive Era',
    authorNationality: 'American',
    emoticons: '🏠🌾🙏💒👨‍👩‍👧',
    notableQuotes: [
      'Faith and family are the foundations of a good life.',
      'The simple life holds the deepest truths.',
      'God watches over those who believe.',
      'Love is the greatest commandment.',
    ],
    publicationYear: 1921,
    setting: 'United States',
    protagonist: 'Young man',
  },
  {
    id: 28152,
    title: 'Sword and Pen',
    author: 'John Algernon Owens',
    genre: 'Biography',
    era: 'Gilded Age',
    authorNationality: 'American',
    emoticons: '⚔️✒️🎖️📖🇺🇸',
    notableQuotes: [
      'The pen is mightier than the sword, but both have their place.',
      'Perseverance is the key to success in all endeavors.',
      'In words we find power; in action, we find purpose.',
      'A true soldier fights with honor.',
    ],
    publicationYear: 1881,
    setting: 'United States',
    protagonist: 'Soldier',
  },
  {
    id: 26,
    title: 'Paradise Lost',
    author: 'John Milton',
    genre: 'Epic Poetry',
    era: 'Restoration',
    authorNationality: 'British',
    emoticons: '😈🍎👼🌳🔥',
    notableQuotes: [
      'Better to reign in Hell than serve in Heaven.',
      'The mind is its own place, and in itself can make a Heaven of Hell.',
      'Long is the way and hard, that out of Hell leads up to Light.',
      'Awake, arise, or be for ever fallen.',
      'Knowledge forbidden? Suspicious, reasonless. Why should their Lord envy them that?',
    ],
    publicationYear: 1667,
    setting: 'Paradise',
    protagonist: 'Man',
  },
] as const;

export const GUTENGUESS_BOOK_COUNT = GUTENGUESS_BOOKS_SOURCE.length;
