/* eslint-disable max-lines -- Data file containing curated book list */
/**
 * PLAIN TEXT source for GutenGuess books.
 * THIS FILE IS GITIGNORED - do not commit!
 *
 * To update books:
 * 1. Edit this file
 * 2. Run: pnpm obfuscate:books
 * 3. Commit the generated gutenguess-books.ts
 */

export interface GutenGuessBook {
  id: number;
  title: string;
  author: string;
  genre: string;
  era: string;
  authorNationality: string;
  emoticons: string;
  notableQuotes: string[];
}

export const GUTENGUESS_BOOKS_SOURCE: readonly GutenGuessBook[] = [
  {
    id: 11,
    title: "Alice's Adventures in Wonderland",
    author: 'Lewis Carroll',
    genre: 'Fantasy',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '🐰🎩🍄🃏👸',
    notableQuotes: [
      "We're all mad here.",
      'Curiouser and curiouser!',
      'Off with her head!',
    ],
  },
  {
    id: 16,
    title: 'Peter Pan',
    author: 'J.M. Barrie',
    genre: 'Fantasy',
    era: 'Edwardian',
    authorNationality: 'Scottish',
    emoticons: '🧚✨🏴‍☠️🐊⭐',
    notableQuotes: [
      'To die will be an awfully big adventure.',
      'All children, except one, grow up.',
    ],
  },
  {
    id: 36,
    title: 'The War of the Worlds',
    author: 'H.G. Wells',
    genre: 'Science Fiction',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '👽🔴🌍💥🛸',
    notableQuotes: [
      'No one would have believed in the last years of the nineteenth century...',
      'The chances of anything coming from Mars are a million to one.',
    ],
  },
  {
    id: 45,
    title: 'Anne of Green Gables',
    author: 'L.M. Montgomery',
    genre: 'Coming-of-Age',
    era: 'Edwardian',
    authorNationality: 'Canadian',
    emoticons: '👧🏠🌸📚💚',
    notableQuotes: [
      "I'm so glad I live in a world where there are Octobers.",
      'Tomorrow is always fresh with no mistakes in it.',
    ],
  },
  {
    id: 55,
    title: 'The Wonderful Wizard of Oz',
    author: 'L. Frank Baum',
    genre: 'Fantasy',
    era: 'Early 20th Century',
    authorNationality: 'American',
    emoticons: '🌪️👠🦁🤖🧙',
    notableQuotes: [
      "There's no place like home.",
      "Toto, I've a feeling we're not in Kansas anymore.",
    ],
  },
  {
    id: 74,
    title: 'The Adventures of Tom Sawyer',
    author: 'Mark Twain',
    genre: 'Adventure',
    era: 'Gilded Age',
    authorNationality: 'American',
    emoticons: '👦🎣🏝️💀🖌️',
    notableQuotes: [
      'Work consists of whatever a body is obliged to do.',
      'The less there is to justify a traditional custom, the harder it is to get rid of it.',
    ],
  },
  {
    id: 76,
    title: 'Adventures of Huckleberry Finn',
    author: 'Mark Twain',
    genre: 'Adventure',
    era: 'Gilded Age',
    authorNationality: 'American',
    emoticons: '🛶🌊👦🏃💫',
    notableQuotes: [
      "All right, then, I'll go to hell.",
      'Human beings can be awful cruel to one another.',
    ],
  },
  {
    id: 84,
    title: 'Frankenstein',
    author: 'Mary Shelley',
    genre: 'Gothic Horror',
    era: 'Romantic',
    authorNationality: 'British',
    emoticons: '⚡🧟💀🏔️🔬',
    notableQuotes: [
      'Beware; for I am fearless, and therefore powerful.',
      'Nothing is so painful to the human mind as a great and sudden change.',
    ],
  },
  {
    id: 120,
    title: 'Treasure Island',
    author: 'Robert Louis Stevenson',
    genre: 'Adventure',
    era: 'Victorian',
    authorNationality: 'Scottish',
    emoticons: '🏴‍☠️💰🗺️🦜⚓',
    notableQuotes: [
      "Fifteen men on the dead man's chest, yo-ho-ho, and a bottle of rum!",
      "Them that die'll be the lucky ones.",
    ],
  },
  {
    id: 158,
    title: 'Emma',
    author: 'Jane Austen',
    genre: 'Romance',
    era: 'Regency',
    authorNationality: 'British',
    emoticons: '👩💕🏡🎭💐',
    notableQuotes: [
      'I always deserve the best treatment because I never put up with any other.',
      'Silly things do cease to be silly if they are done by sensible people.',
    ],
  },
  {
    id: 174,
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    genre: 'Gothic',
    era: 'Victorian',
    authorNationality: 'Irish',
    emoticons: '🖼️👤💀🌹✨',
    notableQuotes: [
      'The only way to get rid of a temptation is to yield to it.',
      'To define is to limit.',
    ],
  },
  {
    id: 244,
    title: 'A Study in Scarlet',
    author: 'Arthur Conan Doyle',
    genre: 'Mystery',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '🔍🎩💉🔴🕵️',
    notableQuotes: [
      'There is nothing new under the sun.',
      'When you have eliminated the impossible, whatever remains must be the truth.',
    ],
  },
  {
    id: 345,
    title: 'Dracula',
    author: 'Bram Stoker',
    genre: 'Gothic Horror',
    era: 'Victorian',
    authorNationality: 'Irish',
    emoticons: '🧛🏰🦇🌙💉',
    notableQuotes: [
      'Listen to them, the children of the night. What music they make!',
      'I am Dracula, and I bid you welcome.',
    ],
  },
  {
    id: 730,
    title: 'Oliver Twist',
    author: 'Charles Dickens',
    genre: 'Social Novel',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '👦🍲🏭💔🎩',
    notableQuotes: [
      'Please, sir, I want some more.',
      'There is something about a roused woman.',
    ],
  },
  {
    id: 768,
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    genre: 'Gothic Romance',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '🌪️💔🏚️👻❤️',
    notableQuotes: [
      "He's more myself than I am.",
      'Whatever our souls are made of, his and mine are the same.',
    ],
  },
  {
    id: 863,
    title: 'The Mysterious Affair at Styles',
    author: 'Agatha Christie',
    genre: 'Mystery',
    era: 'Interwar',
    authorNationality: 'British',
    emoticons: '☠️🔍💊🏠🧓',
    notableQuotes: [
      "Every murderer is probably somebody's old friend.",
      'The simplest explanation is always the most likely.',
    ],
  },
  {
    id: 1184,
    title: 'The Count of Monte Cristo',
    author: 'Alexandre Dumas',
    genre: 'Adventure',
    era: 'Romantic',
    authorNationality: 'French',
    emoticons: '⛓️💎🗡️🏝️💰',
    notableQuotes: [
      'All human wisdom is summed up in two words: wait and hope.',
      'Life is a storm. One day the sun shines and the next day thunder rolls.',
    ],
  },
  {
    id: 1232,
    title: 'The Prince',
    author: 'Niccolò Machiavelli',
    genre: 'Political Philosophy',
    era: 'Renaissance',
    authorNationality: 'Italian',
    emoticons: '👑🗡️🦊🦁📜',
    notableQuotes: [
      'It is better to be feared than loved.',
      'The ends justify the means.',
    ],
  },
  {
    id: 1260,
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    genre: 'Gothic Romance',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '👩📚🏚️🔥❤️',
    notableQuotes: [
      'I am no bird; and no net ensnares me.',
      'Reader, I married him.',
    ],
  },
  {
    id: 1342,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    genre: 'Romance',
    era: 'Regency',
    authorNationality: 'British',
    emoticons: '💃🎩💕📝🏛️',
    notableQuotes: [
      'It is a truth universally acknowledged...',
      'You have bewitched me, body and soul.',
    ],
  },
  {
    id: 1399,
    title: 'Anna Karenina',
    author: 'Leo Tolstoy',
    genre: 'Realist Novel',
    era: 'Victorian',
    authorNationality: 'Russian',
    emoticons: '🚂💔👩❄️💃',
    notableQuotes: [
      'All happy families are alike; each unhappy family is unhappy in its own way.',
      "If you look for perfection, you'll never be content.",
    ],
  },
  {
    id: 1400,
    title: 'Great Expectations',
    author: 'Charles Dickens',
    genre: 'Coming-of-Age',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '👦💰👰🔨⛓️',
    notableQuotes: [
      'I loved her against reason, against promise, against peace.',
      'Suffering has been stronger than all other teaching.',
    ],
  },
  {
    id: 1661,
    title: 'The Adventures of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    genre: 'Mystery',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '🔍🎻🧪💨🎩',
    notableQuotes: [
      'Elementary, my dear Watson.',
      'When you have eliminated the impossible, whatever remains must be the truth.',
    ],
  },
  {
    id: 2600,
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    genre: 'Historical Fiction',
    era: 'Victorian',
    authorNationality: 'Russian',
    emoticons: '⚔️❄️👑💔🇷🇺',
    notableQuotes: [
      'The strongest of all warriors are these two — Time and Patience.',
      'We can know only that we know nothing.',
    ],
  },
  {
    id: 2701,
    title: 'Moby Dick',
    author: 'Herman Melville',
    genre: 'Adventure',
    era: 'American Renaissance',
    authorNationality: 'American',
    emoticons: '🐋🚢⚓🌊😠',
    notableQuotes: [
      'Call me Ishmael.',
      'It is not down on any map; true places never are.',
    ],
  },
  {
    id: 2852,
    title: 'The Hound of the Baskervilles',
    author: 'Arthur Conan Doyle',
    genre: 'Mystery',
    era: 'Edwardian',
    authorNationality: 'British',
    emoticons: '🐕🌫️🏚️🔍💀',
    notableQuotes: [
      'Mr. Holmes, they were the footprints of a gigantic hound!',
      'The world is full of obvious things which nobody observes.',
    ],
  },
  {
    id: 8800,
    title: 'The Divine Comedy',
    author: 'Dante Alighieri',
    genre: 'Epic Poetry',
    era: 'Medieval',
    authorNationality: 'Italian',
    emoticons: '🔥👼😈⭐🚶',
    notableQuotes: [
      'Abandon all hope, ye who enter here.',
      'The path to paradise begins in hell.',
    ],
  },
  {
    id: 64317,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    genre: 'Tragedy',
    era: 'Jazz Age',
    authorNationality: 'American',
    emoticons: '🎉💚🥂🚗💔',
    notableQuotes: [
      'So we beat on, boats against the current.',
      "Can't repeat the past? Why of course you can!",
    ],
  },
  {
    id: 28054,
    title: 'The Brothers Karamazov',
    author: 'Fyodor Dostoevsky',
    genre: 'Philosophical Fiction',
    era: 'Victorian',
    authorNationality: 'Russian',
    emoticons: '👨‍👨‍👦💔⛪💰😈',
    notableQuotes: [
      'The soul is healed by being with children.',
      'If God does not exist, everything is permitted.',
    ],
  },
  {
    id: 203,
    title: "Uncle Tom's Cabin",
    author: 'Harriet Beecher Stowe',
    genre: 'Social Novel',
    era: 'Antebellum',
    authorNationality: 'American',
    emoticons: '⛓️🏠💔🙏✊',
    notableQuotes: [
      'The longest way must have its close.',
      'I never thought my heart could hold so much.',
    ],
  },
  {
    id: 105,
    title: 'Persuasion',
    author: 'Jane Austen',
    genre: 'Romance',
    era: 'Regency',
    authorNationality: 'British',
    emoticons: '💌⚓💕🌊👩',
    notableQuotes: [
      'You pierce my soul. I am half agony, half hope.',
      'There could have been no two hearts so open.',
    ],
  },
  {
    id: 161,
    title: 'Sense and Sensibility',
    author: 'Jane Austen',
    genre: 'Romance',
    era: 'Regency',
    authorNationality: 'British',
    emoticons: '👭💔💕🏡📝',
    notableQuotes: [
      'Know your own happiness.',
      'The more I know of the world, the more I am convinced I shall never see a man whom I can really love.',
    ],
  },
  {
    id: 766,
    title: 'David Copperfield',
    author: 'Charles Dickens',
    genre: 'Bildungsroman',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '👦📖✍️💔🎭',
    notableQuotes: [
      'Whether I shall turn out to be the hero of my own life...',
      'Accidents will occur in the best-regulated families.',
    ],
  },
  {
    id: 145,
    title: 'Middlemarch',
    author: 'George Eliot',
    genre: 'Realist Novel',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '👩🔬💔🏘️📚',
    notableQuotes: [
      'It is never too late to be what you might have been.',
      'What do we live for, if not to make life less difficult for each other?',
    ],
  },
  {
    id: 6130,
    title: 'The Iliad',
    author: 'Homer',
    genre: 'Epic Poetry',
    era: 'Ancient',
    authorNationality: 'Greek',
    emoticons: '⚔️🏛️🐴👑😠',
    notableQuotes: [
      'Sing, O goddess, the anger of Achilles.',
      'There is nothing alive more agonized than man.',
    ],
  },
  {
    id: 996,
    title: 'Don Quixote',
    author: 'Miguel de Cervantes',
    genre: 'Satire',
    era: 'Spanish Golden Age',
    authorNationality: 'Spanish',
    emoticons: '🐴🏰🌾💫🛡️',
    notableQuotes: [
      'Tilting at windmills.',
      'The truth may be stretched thin, but it never breaks.',
    ],
  },
  {
    id: 1497,
    title: 'The Republic',
    author: 'Plato',
    genre: 'Philosophy',
    era: 'Ancient',
    authorNationality: 'Greek',
    emoticons: '🏛️💭⚖️🔥👁️',
    notableQuotes: [
      'The myth of the cave.',
      'Justice in the life and conduct of the State is possible only as first it resides in the hearts of the citizens.',
    ],
  },
  {
    id: 69087,
    title: 'The Murder of Roger Ackroyd',
    author: 'Agatha Christie',
    genre: 'Mystery',
    era: 'Interwar',
    authorNationality: 'British',
    emoticons: '🔪🕵️📓🏠😱',
    notableQuotes: [
      'The truth, however ugly in itself, is always curious and beautiful to seekers after it.',
      'Very few of us are what we seem.',
    ],
  },
  {
    id: 21,
    title: "Aesop's Fables",
    author: 'Aesop',
    genre: 'Fables',
    era: 'Ancient',
    authorNationality: 'Greek',
    emoticons: '🦊🐢🦁🐜📖',
    notableQuotes: [
      'Slow and steady wins the race.',
      'A bird in the hand is worth two in the bush.',
    ],
  },
  {
    id: 1998,
    title: 'Thus Spoke Zarathustra',
    author: 'Friedrich Nietzsche',
    genre: 'Philosophy',
    era: 'Victorian',
    authorNationality: 'German',
    emoticons: '🏔️🦅💫🔥🧙',
    notableQuotes: ['God is dead.', 'What does not kill me makes me stronger.'],
  },
  {
    id: 2641,
    title: 'A Room with a View',
    author: 'E.M. Forster',
    genre: 'Romance',
    era: 'Edwardian',
    authorNationality: 'British',
    emoticons: '🏠🌅💕🇮🇹🪟',
    notableQuotes: [
      'We cast a shadow on something wherever we stand.',
      'Life is easy to chronicle, but bewildering to practice.',
    ],
  },
  {
    id: 408,
    title: 'The Souls of Black Folk',
    author: 'W.E.B. Du Bois',
    genre: 'Essays',
    era: 'Early 20th Century',
    authorNationality: 'American',
    emoticons: '✊🎵📚🌿💭',
    notableQuotes: [
      'The problem of the twentieth century is the problem of the color line.',
      'Either America will destroy ignorance or ignorance will destroy America.',
    ],
  },
  {
    id: 16389,
    title: 'The Enchanted April',
    author: 'Elizabeth von Arnim',
    genre: 'Romance',
    era: 'Interwar',
    authorNationality: 'British',
    emoticons: '🌸🏰🇮🇹☀️💐',
    notableQuotes: [
      'The secret of life is in appreciating its blessings.',
      'Every moment of this April will be alive.',
    ],
  },
  {
    id: 8492,
    title: 'The King in Yellow',
    author: 'Robert W. Chambers',
    genre: 'Horror',
    era: 'Victorian',
    authorNationality: 'American',
    emoticons: '👑💛🎭😱📖',
    notableQuotes: [
      'Have you found the Yellow Sign?',
      'The King in Yellow must not be described.',
    ],
  },
  {
    id: 67979,
    title: 'The Blue Castle',
    author: 'L.M. Montgomery',
    genre: 'Romance',
    era: 'Interwar',
    authorNationality: 'Canadian',
    emoticons: '🏰💙💕🌲✨',
    notableQuotes: [
      "I'll be wicked and frivolous to the end of my days.",
      'Fear is the original sin.',
    ],
  },
  {
    id: 70875,
    title: 'Arrowsmith',
    author: 'Sinclair Lewis',
    genre: 'Social Novel',
    era: 'Jazz Age',
    authorNationality: 'American',
    emoticons: '🔬💉🏥📚🧪',
    notableQuotes: [
      'The purpose of a university is not to produce conformists.',
      'Science is lonely work.',
    ],
  },
  {
    id: 394,
    title: 'Cranford',
    author: 'Elizabeth Gaskell',
    genre: 'Social Novel',
    era: 'Victorian',
    authorNationality: 'British',
    emoticons: '👵🏡🍵👗💬',
    notableQuotes: [
      'Cranford is in possession of the Amazons.',
      'A man is so in the way in the house.',
    ],
  },
  {
    id: 986,
    title: 'Master and Man',
    author: 'Leo Tolstoy',
    genre: 'Novella',
    era: 'Victorian',
    authorNationality: 'Russian',
    emoticons: '❄️🐴💰👨‍🌾🌨️',
    notableQuotes: [
      'What is the meaning of my life?',
      'We can only know that we know nothing.',
    ],
  },
  {
    id: 3600,
    title: 'The Essays of Montaigne',
    author: 'Michel de Montaigne',
    genre: 'Essays',
    era: 'Renaissance',
    authorNationality: 'French',
    emoticons: '📜✍️💭🏰🍷',
    notableQuotes: [
      'Que sais-je? (What do I know?)',
      'The only thing certain is that nothing is certain.',
    ],
  },
] as const;

export const GUTENGUESS_BOOK_COUNT = GUTENGUESS_BOOKS_SOURCE.length;
