/* eslint-disable max-lines -- Data file containing curated book list */
/**
 * OBFUSCATED book data for GutenGuess game.
 * DO NOT EDIT DIRECTLY - regenerate from gutenguess-books-source.ts
 *
 * To update books:
 * 1. Edit gutenguess-books-source.ts (gitignored)
 * 2. Run: pnpm obfuscate:books
 */
import { deobfuscate } from '../utils/obfuscate';

export interface GutenGuessBook {
  id: number;
  title: string;
  author: string;
  genre: string;
  era: string;
  authorNationality: string;
  emoticons: string;
  notableQuotes: string[];
  publicationYear: number;
  setting: string;
  protagonist: string;
}

interface EncodedGutenGuessBook {
  id: number;
  title: string;
  author: string;
  genre: string;
  era: string;
  authorNationality: string;
  emoticons: string;
  notableQuotes: string[];
  publicationYear: string;
  setting: string;
  protagonist: string;
}

export const GUTENGUESS_BOOKS_ENCODED: readonly EncodedGutenGuessBook[] = [
  {
    id: 11,
    title: 'JhkdBgtMBg0xEQwfAhFYGQAKRxwaRTkEG0kVBxYbAgE=',
    author: 'KxADDB1LNkwCBxUWAA==',
    genre: 'IRQaEQ8YDA==',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '🐰🎩🍄🃏👸',
    notableQuotes: [
      'MBBTFwtLFEEcVRcbCEVFDhccSQ==',
      'JAAGDAEeBkgCVRsUCEVOHhcQCAAHABxK',
      'KBMSRRkCAUVQHR8ITA1ICgFY',
      'JRATDABLFFlQARIfTAdIDAwXCRwaAk4KG0lQEhVaAwsNHwwVC1UNChtLFkIdEFoOA0VZAwBZAhsQX04fHUgeVQkOAxUD',
      'MB0bRQcFVVkYEFoNAxdBD0UYClU9Wk4qHQFQARIbGEJeSxERAlUTFwsKAQ0AAAAAAAAM',
    ],
    publicationYear: 'Vk1CUA==',
    setting: 'MBoaAQsZGUweEQ==',
    protagonist: 'PhoBCwlLEkQCGQ==',
  },
  {
    id: 16,
    title: 'NxAAABxLJUwe',
    author: 'LVs5S04pFF8CHB8=',
    genre: 'IRQaEQ8YDA==',
    era: 'IhEDBBwPHEwe',
    authorNationality: 'NBYbERoCBkU=',
    emoticons: '🧚✨🏴‍☠️🐊⭐',
    notableQuotes: [
      'MxpUAQcOVVoZGRZaDgANCgtZBgISEAIHDA0SHB1aDQFbDgsNEgcRSw==',
      'JhkYRQ0DHEEUBx8UQEVIEwYcFwFUCgAOWQ0XBxUNTBBdRQ==',
      'NBAXCgAPVV4EFAhaGAoNHw0cRwcdAgYfWQ0RGx5aHxFfCgweDwFUCgBLAUQcGVoXAxdDAgseSQ==',
      'IwcRBAMYVUkfVRkVAQANHxcMAllUDAhLGkMcDFoNCUVaAhYRRx0VFwpLEEMfAB0SQg==',
    ],
    publicationYear: 'VkxFVA==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'JRoN',
  },
  {
    id: 36,
    title: 'Mx0RRTkKBw0fE1oOBAANPAoLCxEH',
    author: 'L1szS048EEEcBg==',
    genre: 'NBYdAAAIEA02HBkOBQpD',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '👽🔴🌍💥🛸',
    notableQuotes: [
      'KRpUCgAOVVofABYeTA1MHQBZBRAYDAsdEElQHBRaGA1ISwkYFAFUHAsKB15QGhxaGA1ISwsQCRAAAAsFAUVQFh8UGBBfEktXSQ==',
      'Mx0RRQ0DFEMTEAlaAwMNCgsAEx0dCwlLFkIdHBQdTANfBAhZKhQGFk4KB0hQFFoXBQlBAgoXRwEbRQEFEAM=',
      'PhAARQ8IB0IDBloOBAANDBAVAVUbA04YBUwTEFZaBQtZDgkVAhYAFk4dFF4EVRsUCEVOBAoVRwcRAg8ZEUgUVRUPHkVoChcND1UDDBoDVUgeAxMVGRYNDhwcFFs=',
      'JQxUEQYOVVkfGRZaAwMNCkUbDhkYDAEFVUkVFA4SH0VACgtZDxQHRQwEAEoYAVoSBRYNCQwLEx0GDAkDAQ0fE1oOBAANLgQLEx1a',
    ],
    publicationYear: 'Vk1NXQ==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'KRQGFw8fGl8=',
  },
  {
    id: 45,
    title: 'JhsaAE4EEw03Bx8fAkVqCgcVAgY=',
    author: 'K1s5S04mGkMEEhUXCRdU',
    genre: 'JBoZDAAMWEIWWDsdCQ==',
    era: 'IhEDBBwPHEwe',
    authorNationality: 'JBQaBAoCFEM=',
    emoticons: '👧🏠🌸📚💚',
    notableQuotes: [
      'LlIZRR0EVUocFB5aJUVBAhMcRxwaRQ9LAkICGR5aGw1IGQBZEx0RFwtLFF8VVTUZGApPDhcKSQ==',
      'MxoZChwZGlpQHAlaDQlaChwKRxMGAB0DVVoZARJaAgoNBgwKExQfAB1LHENQHA5U',
      'LBwaARwOEQ0DBRMIBRFeSwQLAlUaChpLBkJQBhkbHgZISwQKRzxUEB0OEQ0EGloOBAxDAEs=',
      'LgFTFk4JEEgeVRcDTABVGwALDhAaBgtLAUURAVoDAxANCAQXRxsRBBwHDA0RGQ0bFRYNDgsTCAxUEQYCG0oDVRMcTBxCHkUUBh4RRRsbVVQfAAhaAQxDD0UfDgcZCRdLAUURAVoDAxANHAwVC1s=',
    ],
    publicationYear: 'VkxEXQ==',
    setting: 'JBQaBAoK',
    protagonist: 'IBwGCQ==',
  },
  {
    id: 55,
    title: 'Mx0RRTkEG0kVBxwPAEV6Ah8YFRFUCghLOlc=',
    author: 'K1tUIxwKG0ZQNxsPAQ==',
    genre: 'IRQaEQ8YDA==',
    era: 'IhQGCRdLRx0EHVo5CQtZHhcA',
    authorNationality: 'JhgRFwcIFEM=',
    emoticons: '🌪️👠🦁🤖🧙',
    notableQuotes: [
      'Mx0RFwtMBg0eGloKAARODkUVDh4RRQYEGEhe',
      'MxoACkJLPAoGEFobTANIDgkQCRJUEgtMB0hQGxUOTAxDSy4YCQYVFk4KG1QdGggfQg==',
      'JlUcAA8ZAQ0ZBloUAxENARAdABAQRQwSVUUfAloXGQZFSxwWElUYChgOWQ0SAA5aDhwNAwoORxgBBgZLDEIFVRsICUVBBBMcA1UWHE4EAUUVBwlU',
      'PhoBRQYKA0hQBRYfAhFUSwofRxYbEBwKEkhcVTNaDQgNGBALAltUJAIHVVQfAFoUCQBJSwwKRxYbCwgCEUgeFh9aBQsNEgoMFQYRCQhF',
    ],
    publicationYear: 'VkxEVQ==',
    setting: 'MhsdEQsPVX4EFA4fHw==',
    protagonist: 'PhoBCwlLEkQCGQ==',
  },
  {
    id: 74,
    title: 'Mx0RRS8PA0geAQ8ICRYNBANZMxoZRT0KAlQVBw==',
    author: 'KhQGDk4/AkwZGw==',
    genre: 'JhECAAAfAF8V',
    era: 'IBwYAQsPVWwXEA==',
    authorNationality: 'JhgRFwcIFEM=',
    emoticons: '👦🎣🏝️💀🖌️',
    notableQuotes: [
      'MBoGDk4IGkMDHAkOH0VCDUUODxQAABgOBw0RVRgVCBwNAhZZCBcYDAkOEQ0EGloeA0s=',
      'Mx0RRQIOBl5QARIfHgANAhZZExpUDxsYAUQWDFobTBFfCgEQExwbCw8HVU4FBg4VAUkNHw0cRx0VFwoOBw0ZAVoTH0VZBEUeAgFUFwcPVUIWVRMOQg==',
      'LxBUDQ8PVUkZBhkVGgBfDgFZBlUTFwsKAQ0cFA1aAwMNAxAUBhtUBA0fHEIeT1oOA0VACg4cRxRUCA8FVU4fAx8OTAQNHw0QCRJYRQEFGVRQGBsRCUVZAwBZEx0dCwlLEUQWExMZGQlZSxEWRxQAEQ8CGwM=',
      'KBMAAABHVVkYEFoJGRdIGBFZEBQNRRoEVU4fGwwfFUVAAhYQCRMbFwMKAUQfG1oTH0VZBEUNAhkYRRoDEA0DAQgTDxENHxcMEx1a',
    ],
    publicationYear: 'Vk1DUw==',
    setting: 'MhsdEQsPVX4EFA4fHw==',
    protagonist: 'PhoBCwlLF0IJ',
  },
  {
    id: 76,
    title: 'JhECAAAfAF8VBloVCkVlHgYSCxAWABwZDA02HBQU',
    author: 'KhQGDk4/AkwZGw==',
    genre: 'JhECAAAfAF8V',
    era: 'IBwYAQsPVWwXEA==',
    authorNationality: 'JhgRFwcIFEM=',
    emoticons: '🛶🌊👦🏃🌙',
    notableQuotes: [
      'JhkYRRwCEkUEWVoOBABDR0UwQBkYRQkEVVkfVRIfAAkD',
      'LwAZBABLF0gZGx0JTAZMBUUbAlUVEggeGQ0TBw8fAEVZBEUWCRBUBAAEAUUVB1Q=',
      'LgFUEg8ZGwoEVRQVTBBeDkUNCFUAFxdLAUJQHRMeCUVEH0UfFRoZRSYCGAM=',
      'Mx0VEU4CBg0aAAkOTBFFDkUOBgxUEgcfHQ0DGhcfTBVIBBUVAltUMQYODA0XEA5aCApaBUUWCVUVRRoDHEMXVQ0SCQsNHw0cHlUQCgBMAQ0bGxUNTAtCHw0QCRJUBAwEAFlQHA5U',
    ],
    publicationYear: 'Vk1MUQ==',
    setting: 'MhsdEQsPVX4EFA4fHw==',
    protagonist: 'PhoBCwlLF0IJ',
  },
  {
    id: 84,
    title: 'IQcVCwUOG14EEBMU',
    author: 'KhQGHE44HUgcGR8D',
    genre: 'IBoADQcIVWUfBwgVHg==',
    era: 'NRoZBAAfHE4=',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '⚡🧟💀🏔️🔬',
    notableQuotes: [
      'JRADBBwOTg0WGghaJUVMBkUfAhQGCQsYBgFQFBQeTBFFDhccARoGAE4bGloVBxwPAEs=',
      'KRoADQcFEg0ZBloJA0VdCgwXAQAYRRoEVVkYEFoSGQhMBUUUDhsQRQ8YVUxQEggfDRENCgsdRwYBAQoOGw0THRsUCwAD',
      'LlUbEAkDAQ0EGloYCUVZAxxZJhEVCEJLF1gEVTNaDQgNGQQNDxAGRRoDEA0WFBYWCQsNCgseAhla',
      'KxwSAEJLFEEEHRUPCw0NAhFZChQNRQEFGVRQFx9aDQsNCgYaEhgBCQ8fHEIeVRUcTARDDBAQFB1YRQcYVUkVFAhaGAoNBgBX',
    ],
    publicationYear: 'Vk1FXQ==',
    setting: 'IgAGCh4O',
    protagonist: 'NBYdAAAfHF4E',
  },
  {
    id: 120,
    title: 'MwcRBB0eB0hQPAkWDQtJ',
    author: 'NRoWABwfVWEfABMJTDZZDhMcCQYbCw==',
    genre: 'JhECAAAfAF8V',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'NBYbERoCBkU=',
    emoticons: '🏴‍☠️💰🗺️🦜⚓',
    notableQuotes: [
      'IRwSEQsOGw0dEBRaAwsNHw0cRxERBApLGEweUglaDw1IGBFVRwwbSAYEWEUfWVobAgENCkUbCAEACQtLGktQBw8XTQ==',
      'Mx0RCE4fHUwEVR4TCUJBB0UbAlUADQtLGVgTHgNaAwtIGEs=',
      'NxwRBgsYVUIWVR8TCw1ZSkUpDhAXAB1LGktQEBMdBBEM',
      'NB0dEwsZVUAJVQ4TAQdIGRZY',
    ],
    publicationYear: 'Vk1MVg==',
    setting: 'JBQGDAwJEEwe',
    protagonist: 'PhoBCwlLF0IJ',
  },
  {
    id: 158,
    title: 'IhgZBA==',
    author: 'LRQaAE4qAF4EEBQ=',
    genre: 'NRoZBAAIEA==',
    era: 'NRATAAAIDA==',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '👩💕🏡🎭💐',
    notableQuotes: [
      'LlUVCRkKDF5QER8JCRdbDkUNDxBUBwsYAQ0EBx8bGAhIBRFZBRAXBBsYEA05VRQfGgBfSxUME1UBFU4cHFkYVRsUFUVCHw0cFVs=',
      'NBwYCRdLAUUZGx0JTAFCSwYcBgYRRRoEVU8VVQkTAAlUSwwfRwEcABdLFF8VVR4VAgANCRxZFBAaFgcJGUhQBR8VHAlIRQ==',
      'KBsRRQYKGUtQGhxaGA1ISxIWFRkQRQ0KG0MfAVoPAgFIGRYNBhsQRRoDEA0AGR8bHxBfDhZZCBNUEQYOVUIEHR8IQg==',
      'Mx0RFwtLFF8VVQofAxVBDkUODxpUEQYOVUAfBx9aFQpYSwEWRxMbF04fHUgdWVoOBAANBwAKFFUADQsSVVoZGRZaCAoNDQoLRwEcAAMYEEEGEAlU',
    ],
    publicationYear: 'Vk1FUA==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'PhoBCwlLAkIdFBQ=',
  },
  {
    id: 174,
    title: 'Mx0RRT4CFlkFBx9aAwMNLwoLDhQaRSkZFFQ=',
    author: 'KAYXBBxLIkQcER8=',
    genre: 'IBoADQcI',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'LgcdFgY=',
    emoticons: '🖼️👤💀🌹✨',
    notableQuotes: [
      'Mx0RRQEFGVRQAhsDTBFCSwIcE1UGDApLGktQFFoOCQhdHwQNDhoaRQcYVVkfVQMTCQlJSxEWRxwASw==',
      'MxpUAQsNHEMVVRMJTBFCSwkQChwASw==',
      'LlUcBBgOVUoCGg0UTBFCSwkWERBUFgsIB0gTDFQ=',
      'PhoBEQZLHF5QARIfTApDDkUNDxwaAk4cGl8EHVoSDRNEBQJX',
      'JRAcDAAPVUgGEAgDTABVGhAQFBwAAE4fHUQeEloOBARZSwABDgYAAApHVVkYEAgfTBJMGEUKCBgREQYCG0pQAQgbCwxORQ==',
    ],
    publicationYear: 'Vk1NVQ==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'PhoBCwlLGEwe',
  },
  {
    id: 244,
    title: 'JlUnERsPDA0ZG1opDwRfBwAN',
    author: 'JgcADRsZVW4fGxsUTCFCEgkc',
    genre: 'KgwHEQsZDA==',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '🔍🎩💉🔴🕵️',
    notableQuotes: [
      'Mx0RFwtLHF5QGxUOBAxDDEUXAgJUEAAPEF9QARIfTBZYBUs=',
      'MB0RC04SGlhQHRsMCUVIBwwUDhsVEQsPVVkYEFoTARVCGBYQBRkRSU4cHUwEEAwfHkVfDggYDhsHRQMeBllQFx9aGA1ISxELEgEcSw==',
      'LlUXCgAYHEkVB1oOBARZSwRZChQaQh1LF18RHBRaAxdEDAwXBhkYHE4CBg0cHBEfTAQNBwwNExkRRQsGBVkJVRsOGAxORQ==',
      'Mx0RFwtLHF5QGxUOBAxDDEUUCAcRRQoOFkgAARMMCUVZAwQXRxQaRQEJA0QfAAlaCgROH0s=',
    ],
    publicationYear: 'Vk1MUg==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'IxAAAA0fHFsV',
  },
  {
    id: 345,
    title: 'IwcVBhsHFA==',
    author: 'JQcVCE44AUIbEAg=',
    genre: 'IBoADQcIVWUfBwgVHg==',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'LgcdFgY=',
    emoticons: '🧛🏰🦇🌙💉',
    notableQuotes: [
      'KxwHEQsFVVkfVQ4SCQgBSxERAlUXDQcHEV8VG1oVCkVZAwBZCRwTDRpFVXoYFA5aARBeAgZZEx0RHE4GFEYVVA==',
      'LlUVCE4vB0wTABYbQEVMBQFZLlUWDApLDEIFVQ0fAAZCBgBX',
      'Mx0RRQwHGkIUVRMJTBFFDkUVDhMRRA==',
      'Mx0RFwtLFF8VVR4bHg5DDhYKAgZUDABLGUQWEFobAgENHw0cFRBUBBwOVUEZEhIOH0s=',
      'MBBUCQsKB0NQEwgVAUVLCgwVEgcRSU4FGllQEwgVAUVeHgYaAgYHRA==',
    ],
    publicationYear: 'Vk1NUg==',
    setting: 'MwcVCx0SGVsRGxMb',
    protagonist: 'KhQa',
  },
  {
    id: 730,
    title: 'KBkdEwsZVXkHHAkO',
    author: 'JB0VFwIOBg00HBkRCQte',
    genre: 'NBoXDA8HVWMfAx8W',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '👦🍲🏭💔🎩',
    notableQuotes: [
      'NxkRBB0OWQ0DHAhWTCwNHAQXE1UHCgMOVUAfBx9U',
      'Mx0RFwtLHF5QBhUXCRFFAgseRxQWChsfVUxQBxUPHwBJSxIWChQaSw==',
      'Mx0RRQIKAg0ZBlobAkVMGBZX',
      'IxwTCwcfDAFQFBQeTABbDgtZDxoYDAAOBl5QARUVQEVeBAgcExwZAB1HVUwCEFoXAxdISxQMAgYADAEFBg0fE1oZAwRZSwQXA1UDBAcYAU4fFA5aGA1MBUUKCBgRRR4OGl0cEFoTAQRKAgscSQ==',
    ],
    publicationYear: 'Vk1HUg==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'JRoN',
  },
  {
    id: 768,
    title: 'MAAADQsZHEMXVTIfBQJFHxY=',
    author: 'IhgdCRdLN18fGw7CkQ==',
    genre: 'IBoADQcIVX8fGBsUDwA=',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '🌪️💔🏚️👻❤️',
    notableQuotes: [
      'LxBTFk4GGl8VVRcDHwBBDUUNDxQaRSdLFEBe',
      'MB0VEQsdEF9QGg8ITBZCHgkKRxQGAE4GFEkVVRUcQEVFAhZZBhsQRQMCG0hQFAgfTBFFDkUKBhgRSw==',
      'LlUcBBgOVUMfAVoYHgpGDgtZHhoBF04DEEwCAeKBrgMDEA0DBA8CVRYXAQAQQ1AcDlQ=',
      'JRBUEgcfHQ0dEFobABJMEhbiga0TFB8ATgobVFATFQgB4oGxSRkMDwJVGQBOBhRJUQ==',
      'LlUXBAAFGllQGRMMCUVaAhERCAAARQMSVUEZEx9bTCwNCAQXCRoARQICA0hQAhMOBApYH0UUHlUHChsHVA==',
    ],
    publicationYear: 'Vk1AUg==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'MBoZBAA=',
  },
  {
    id: 863,
    title: 'Mx0RRSMSBlkVBxMVGRYNKgMfBhwGRQ8fVX4EDBYfHw==',
    author: 'JhIVEQYKVW4YBxMJGAxI',
    genre: 'KgwHEQsZDA==',
    era: 'LhsAABwcFF8=',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '☠️🔍💊🏠🧓',
    notableQuotes: [
      'IgMRFxdLGFgCER8ICRcNAhZZFwcbBw8JGVRQBhUXCQdCDxxeFFUbCQpLE18ZEBQeQg==',
      'Mx0RRR0CGF0cEAkOTABVGwkYCRQADAEFVUQDVRsWGwRUGEUNDxBUCAEYAQ0cHBEfABwD',
      'Mx0RRQcGBUIDBhMYAAANCAoMCxFUCwEfVUURAx9aBARdGwAXAhFYRRoDEF8VExUICUVZAwBZDhgECh0YHE8cEFoXGRZZSwccRwUbFh0CF0EVWw==',
      'LlUVCE4FGllQHh8fHAxDDEUbBhYfRQgKFlkDW1o/GgBfEkUfBhYARRoDFFlQPFoRAgpaSwwKRxwaRRcEAF9QBRUJHwBeGAwWCVs=',
    ],
    publicationYear: 'VkxGVQ==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'IxAAAA0fHFsV',
  },
  {
    id: 1184,
    title: 'Mx0RRS0EAEMEVRUcTChCBREcRzYGDB0fGg==',
    author: 'JhkRHQ8FEV8VVT4PAQRe',
    genre: 'JhECAAAfAF8V',
    era: 'NRoZBAAfHE4=',
    authorNationality: 'IQcRCw0D',
    emoticons: '⛓️💎🗡️🏝️💰',
    notableQuotes: [
      'JhkYRQYeGEweVQ0THwFCBkUQFFUHEAMGEElQAApaBQsNHxIWRwIbFwoYTw0HFBMOTARDD0URCAURSw==',
      'KxwSAE4CBg0RVQkOAxdARUU2CRBUAQ8SVVkYEFoJGQsNGA0QCRAHRQ8FEQ0EHR9aAgBVH0UdBgxUEQYeG0kVB1oIAwlBGEs=',
      'LlUVCE4FGllQBQgVGQEBSwcME1U9RQ8GVUURBQoDV0VMBQFZDxQEFQcFEF4DVRgWBQtJGElZLlUADQcFHgFQGBUICUVZAwQXRwUGDAoOWw==',
      'MhsADAJLAUUVVR4bFUVaAwAXRzIbAU4cHEEcVR4fBQJDSxEWRwcREwsKGQ0EHR9aChBZHhccRwEbRQMKGwFQFBYWTA1YBgQXRwIdFgoEGA0ZBloZAwtZCgwXAhFUDABLAUUVBh9aGBJCSxIWFREHX048FEQEVRsUCEVlBBUcSQ==',
    ],
    publicationYear: 'Vk1AUQ==',
    setting: 'KhAQDBoOB18RGx8bAg==',
    protagonist: 'NwcdFgEFEF8=',
  },
  {
    id: 1232,
    title: 'Mx0RRT4ZHEMTEA==',
    author: 'KRwXBgEHwocNPRQZEgUEWw4JFQ4=',
    genre: 'NxoYDBoCFkwcVSoSBQlCGAoJDww=',
    era: 'NRAaBAcYBkweFh8=',
    authorNationality: 'LgEVCQcKGw==',
    emoticons: '👑🗡️🦊🦁📜',
    notableQuotes: [
      'LgFUDB1LF0gEAR8ITBFCSwccRxMRBBwOEQ0EHRsUTAlCHQAdSQ==',
      'Mx0RRQsFEV5QHw8JGAxLEkUNDxBUCAsKG15e',
      'KhAaRQ8ZEA0UBxMMCQsNCRxZEwIbRR4ZHEMTHAobAEVEBhUMCwYRFlRLGUIGEFobAgENDQAYFVs=',
      'KRACABxLFFkEEBcKGEVZBEUODhtUBxdLE0ICFh9aGw1MH0UaBhtUBwtLAkIeVRgDTAFICAAJExwbC0A=',
    ],
    publicationYear: 'VkBHVw==',
    setting: 'LgEVCRc=',
    protagonist: 'NQAYABw=',
  },
  {
    id: 1260,
    title: 'LRQaAE4uDF8V',
    author: 'JB0VFwIEAVkVVTgIAwtZwoA=',
    genre: 'IBoADQcIVX8fGBsUDwA=',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '👩📚🏚️🔥❤️',
    notableQuotes: [
      'LlUVCE4FGg0SHAgeV0VMBQFZCRpUCwsfVUgeBhQbHgBeSwgcSQ==',
      'NRAVAQsZWQ05VRcbHhdEDgFZDxwZSw==',
      'LlUDChsHEQ0RGQ0bFRYNGQQNDxAGRQwOVUURBQoDTBFFCgtZAxwTCwcNHEgUWw==',
      'LlUXBBwOVUsfB1oXFRZIBwNXRyEcAE4GGl8VVQkVAAxZChcAS1UADQtLGEICEFozTBZFCgkVRwcRFh4OFllQGAMJCQlLRQ==',
      'IxpUHAEeVVkYHBQRTCwNCghZBhtUBBsfGkARARUUU+KBsUxLCBgEHR0LC0sCRAQdFQ8YRUsOABUOGxMWUQ==',
    ],
    publicationYear: 'Vk1AUg==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'IBoCABwFEF4D',
  },
  {
    id: 1342,
    title: 'NwcdAQtLFEMUVSoICQ9YDwwaAg==',
    author: 'LRQaAE4qAF4EEBQ=',
    genre: 'NRoZBAAIEA==',
    era: 'NRATAAAIDA==',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '💃🎩💕📝🏛️',
    notableQuotes: [
      'LgFUDB1LFA0EBw8OBEVYBQwPAgcHBAIHDA0RFhEUAxJBDgEeAhFaS0A=',
      'PhoBRQYKA0hQFx8NBRFOAwAdRxgRSU4JGkkJVRsUCEVeBBAVSQ==',
      'LlUXChsHEQ0VFAkTABwNDQoLABwCAE4DHF5QBQgTCAABSwwfRx0RRQYKEQ0eGg5aAQpfHwwfDhAQRQMCG0he',
      'KgxUAgEEEQ0fBRMUBQpDSwoXBBBUCQEYAQFQHAlaAApeH0UfCAcREwsZWw==',
      'JlUYBAoSUl5QHBcbCwxDChEQCBtUDB1LA0gCDFoIDRVED0s=',
    ],
    publicationYear: 'Vk1FVg==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'PhoBCwlLAkIdFBQ=',
  },
  {
    id: 1399,
    title: 'JhsaBE4gFF8VGxMUDQ==',
    author: 'KxAbRToEGV4EGgM=',
    genre: 'NRAVCQcYAQ0+GgwfAA==',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'NQAHFgcKGw==',
    emoticons: '🚂💔👩❄️💃',
    notableQuotes: [
      'JhkYRQYKBV0JVRwbAQxBAgAKRxQGAE4KGUQbEEFaCQROA0UMCR0VFR4SVUsRGBMWFUVEGEUMCR0VFR4SVUQeVRMOH0VCHAtZEBQNSw==',
      'LhNUHAEeVUEfGhFaCgpfSxUcFRMRBhoCGkNcVQMVGUJBB0UXAgMRF04JEA0TGhQOCQtZRQ==',
      'LxBUFhoOBV0VEVoeAxJDR0UNFQwdCwlLG0IEVQ4VTAlCBA5ZCxoaAk4KAQ0YEAhWTAReSwwfRwYcAE4cEF8VVQ4SCUVeHgtX',
      'NRAHFQsIAQ0HFAlaBQtbDgsNAhFUEQFLFkIGEAhaGA1ISwAUFwENRR4HFE4VVQ0SCRdISwkWERBUFgYEAEEUVRgfQg==',
    ],
    publicationYear: 'Vk1DUg==',
    setting: 'NQAHFgcK',
    protagonist: 'MBoZBAA=',
  },
  {
    id: 1400,
    title: 'IAcRBBpLMFUAEBkODRFEBAsK',
    author: 'JB0VFwIOBg00HBkRCQte',
    genre: 'JBoZDAAMWEIWWDsdCQ==',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '👦💰👰🔨⛓️',
    notableQuotes: [
      'LlUYChgOEQ0YEAhaDQJMAgsKE1UGAA8YGkNcVRsdDQxDGBFZFwcbCAcYEAFQFB0bBQteH0UJAhQXAEA=',
      'NAASAwsZHEMXVRIbH0VPDgAXRwYAFwEFEkgCVQ4SDQsNCgkVRxoADQsZVVkVFBkSBQtKRQ==',
      'MBBUCwsOEQ0eEAwfHkVPDkUYFB0VCAsPVUIWVRUPHkVZDgQLFFs=',
      'LhtUBE4cGl8UWVozTBJMGEUNCBpUBgEcFF8UGQNaGAoNDwpZEB0VEU4iVUYeEA1aGAoNCQBZFRwTDRpHVUwDVTNaBARJSwccAhtUEQEEVU4fAhsICAlUSxEWRxQCCgcPVUkfHBQdTBJFChFZLlUfCwscVVkfVRgfTBJfBAseSQ==',
    ],
    publicationYear: 'Vk1CVA==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'JRoN',
  },
  {
    id: 1661,
    title: 'Mx0RRS8PA0geAQ8ICRYNBANZNB0RFwIEFkZQPRUWAQBe',
    author: 'JgcADRsZVW4fGxsUTCFCEgkc',
    genre: 'KgwHEQsZDA==',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '🔍🎻🧪💨🎩',
    notableQuotes: [
      'IhkRCAsFAUwCDFZaARwNDwAYFVUjBBoYGkNe',
      'MB0RC04SGlhQHRsMCUVIBwwUDhsVEQsPVVkYEFoTARVCGBYQBRkRSU4cHUwEEAwfHkVfDggYDhsHRQMeBllQFx9aGA1ISxELEgEcSw==',
      'Mx0RFwtLHF5QGxUOBAxDDEUUCAcRRR0fHEAFGRsOBQtKSxERBhtUBE4IFF4VVQ0SCRdISwAPAgcNEQYCG0pQEhUfH0VMDAQQCQYARRcEAAM=',
      'LlUaABgOBw0XAB8JH0sNIhFZDgZUBE4YHUITHhMUC0VFCgcQE+KBoRAAHR8HWBMBEwwJRVkERQ0PEFQJAQwcThEZWhwNBlgHEQBJ',
    ],
    publicationYear: 'Vk1NVw==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'IxAAAA0fHFsV',
  },
  {
    id: 2600,
    title: 'MBQGRQ8FEQ0gEBsZCQ==',
    author: 'KxAbRToEGV4EGgM=',
    genre: 'LxwHEQEZHE4RGVo8BQZZAgoX',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'NQAHFgcKGw==',
    emoticons: '⚔️❄️👑💔🇷🇺👨‍👩‍👧',
    notableQuotes: [
      'Mx0RRR0fB0IeEh8JGEVCDUUYCxlUEg8ZB0QfBwlaDRdISxERAgYRRRocGg3igaRVLhMBAA0KCx1HJRURBw4bThVb',
      'MBBUBg8FVUYeGg1aAwtBEkUNDxQARRkOVUYeGg1aAgpZAwwXAFs=',
      'KRoADQcFEg0ZBloJA0VDDgYcFAYVFxdLE0ICVRtaFQpYBQJZChQaRQ8YVVkYEFoZAwhdCgsARxoSRQcFAUgcGRMdCQtZSxIWChAaSw==',
      'LhNUABgOB1QfGx9aCgpYDA0NRxMbF04fHUgZB1oVGwsNCAoXERwXEQcEG15QARIfHgANHAoMCxFUBwtLG0JQAhsIQg==',
    ],
    publicationYear: 'Vk1CXA==',
    setting: 'NQAHFgcK',
    protagonist: 'KhQa',
  },
  {
    id: 2701,
    title: 'KhoWHE4vHE4b',
    author: 'LxAGCA8FVWAVGQwTAAlI',
    genre: 'JhECAAAfAF8V',
    era: 'JhgRFwcIFENQJx8UDQxeGAQXBBA=',
    authorNationality: 'JhgRFwcIFEM=',
    emoticons: '🐋🚢⚓🌊😠',
    notableQuotes: [
      'JBQYCU4GEA05BhIXDQBBRQ==',
      'LgFUDB1LG0IEVR4VGwsNBAtZBhsNRQMKBRZQAQgPCUVdBwQaAgZUCwsdEF9QFAgfQg==',
      'LlUfCwEcVUMfAVobAAkNHw0YE1UZBBdLF0hQFhUXBQtKR0UbEgFUBwtLHFlQAhIbGEVEH0UODhkYSU4iUkEcVR0VTBFCSwwNRxkVEAkDHEMXWw==',
      'JRAAEQsZVVkfVQkWCQBdSxIQEx1UBE4YGk8VB1oZDQtDAgcYC1UADQ8FVUxQEQgPAg5IBUU6DwcdFhoCFENe',
    ],
    publicationYear: 'Vk1BVA==',
    setting: 'NxQXDAgCFg0/Fh8bAg==',
    protagonist: 'NBQdCQEZ',
  },
  {
    id: 2852,
    title: 'Mx0RRSYEAEMUVRUcTBFFDkU7BgYfABwdHEEcEAk=',
    author: 'JgcADRsZVW4fGxsUTCFCEgkc',
    genre: 'KgwHEQsZDA==',
    era: 'IhEDBBwPHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '🐕🌫️🏚️🔍💀',
    notableQuotes: [
      'KgdaRSYEGUAVBlZaGA1IEkUOAgcRRRoDEA0WGhUOHBdEBREKRxoSRQ9LEkQXFBQOBQYNAwoMCRFV',
      'Mx0RRRkEB0EUVRMJTANYBwlZCBNUCgwdHEIFBloOBAxDDBZZEB0dBgZLG0ISGh4DTApPGAALERAHSw==',
      'IgMdCU4CG0kVEB5aBRYNHw0cRxgVC04cHUJQHRsJTAtCH0UWCRBUEgEGFENQARVaAQpYGQtZDxwZSw==',
      'Mx0RFwtLHF5QGxUOBAxDDEUUCAcRRR0fHEAFGRsOBQtKSxERBhtUBE4IFF4VVQ0SCRdISwAPAgcNEQYCG0pQEhUfH0VMDAQQCQYARRcEAAM=',
    ],
    publicationYear: 'VkxEVw==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'IxAAAA0fHFsV',
  },
  {
    id: 8800,
    title: 'Mx0RRSoCA0QeEFo5AwhIDxw=',
    author: 'IxQaEQtLNEEZEhITCRdE',
    genre: 'IgUdBk47GkgEBwM=',
    era: 'KhAQDAsdFEE=',
    authorNationality: 'LgEVCQcKGw==',
    emoticons: '🔥👼😈⭐🚶',
    notableQuotes: [
      'JhcVCwoEGw0RGRZaBApdDklZHhBUEgYEVUgeAR8ITA1IGQBX',
      'Mx0RRR4KAUVQARVaHARfCgEQFBBUBwsMHEMDVRMUTA1IBwlX',
      'LhtUEQYOVUAZER4WCUVCDUUNDxBUDwEeB0MVDFoVCkVCHhdZCxwSAEJLPA0TFBcfTBFCSwgAFBAYA04CGw0RVR4bHg4NHAoWA1s=',
      'Mx0RFwtLHF5QGxVaCxdIChEcFVUHChwZGlpQARIbAkVZBEULAhYVCQJLHUwABRMUCRZeSwwXRwEdCAsYVUIWVRcTHwBfEks=',
      'KxoCAEJLAUURAVoXAxNIGEUNDxBUFhsFVUweEVoOBAANBBERAgdUFhoKB15e',
    ],
    publicationYear: 'VkZGVQ==',
    setting: 'JhMAABwHHEsV',
    protagonist: 'NxwYAhwCGA==',
  },
  {
    id: 64317,
    title: 'Mx0RRSkZEEwEVT0bGBZPEg==',
    author: 'IVtUNg0EAVlQMxMOFgJIGQQVAw==',
    genre: 'MwcVAgsPDA==',
    era: 'LRQOH04qEkg=',
    authorNationality: 'JhgRFwcIFEM=',
    emoticons: '🎉💚🥂🚗💔',
    notableQuotes: [
      'NBpUEgtLF0gRAVoVAkkNCQoYEwZUBAkKHEMDAVoOBAANCBALFRAaEUA=',
      'JBQaQhpLB0gAEBsOTBFFDkUJBgYAWk48HVRQGhxaDwpYGRYcRwwbEE4IFENR',
      'LhtUCBdLDEIFGx0fHkVMBQFZChoGAE4dAEEeEAgbDglISxwcBgcHRQMSVUsRARIfHkVKChMcRxgRRR0EGEhQFB4MBQZIRQ==',
      'LlUcCh4OVV4YEF0WAEVPDkUYRxMbCgLigb8UDRIQGw8YDEseCVkLHAARAg5VSx8aFlQ=',
      'NRAHABwdHEMXVRAPCAJADgsNFFUdFk4KVUARAQ4fHkVCDUUQCRMdCwcfEA0YGgofQg==',
    ],
    publicationYear: 'VkxGUA==',
    setting: 'MhsdEQsPVX4EFA4fHw==',
    protagonist: 'KRQGFw8fGl8=',
  },
  {
    id: 28054,
    title: 'Mx0RRSwZGlkYEAgJTC5MGQQUBg8bEw==',
    author: 'IQwbAQEZVWkfBg4VCRNeABw=',
    genre: 'Nx0dCQEYGl0YHBkbAEVrAgYNDhoa',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'NQAHFgcKGw==',
    emoticons: '👨‍👨‍👦💔⛪💰😈⚖️',
    notableQuotes: [
      'Mx0RRR0EAEFQHAlaBABMBwAdRxcNRQwOHEMXVQ0TGA0NCA0QCxEGAABF',
      'LhNUIgEPVUkfEAlaAgpZSwABDgYASU4OA0gCDA4SBQtKSwwKRwURFwMCAVkVEVQ=',
      'JhcbEwtLFEEcWVoeA0VDBBFZCxwRRRoEVVQfAAgJCQlLRQ==',
      'Mx0RRQMSBlkVBwNaAwMNAxAUBhtUABYCBlkVGxkfTAlEDhZZCRoARQcFVUcFBg5aHxFMEgwXAFUVCQcdEAFQFw8OTAxDSwMQCREdCwlLBkIdEA4SBQtKSxEWRxkdEwtLE0ICWw==',
    ],
    publicationYear: 'Vk1MVQ==',
    setting: 'NQAHFgcK',
    protagonist: 'PhoBCwlLGEwe',
  },
  {
    id: 203,
    title: 'MhsXCQtLIUIdUglaLwRPAgs=',
    author: 'LxQGFwcOAQ0yEB8ZBABfSzYNCAIR',
    genre: 'NBoXDA8HVWMfAx8W',
    era: 'JhsAAAwOGUEFGA==',
    authorNationality: 'JhgRFwcIFEM=',
    emoticons: '⛓️🏠💔🙏✊',
    notableQuotes: [
      'Mx0RRQIEG0oVBg5aGwRUSwgMFAFUDQ8dEA0ZAQlaDwlCGABX',
      'LlUaABgOBw0EHRUPCw1ZSwgARx0RBBwfVU4fABYeTA1CBwFZFBpUCBsIHQM=',
      'NBpUHAEeVUwCEFoOBAANBwwNExkRRRkEGEweVQ0SA0VaGQoNAlUADQtLF0IfHloOBARZSxYNBgcAAApLAUUZBlodHgBMH0UOBgda',
      'JhsNRQMCG0lQARIbGEVEGEUaBgUVBwIOVUIWVQgfDQkNGAoLFRoDRQcYVU4RBRsYAAANBANZABobAUA=',
    ],
    publicationYear: 'Vk1BVw==',
    setting: 'MhsdEQsPVX4EFA4fHw==',
    protagonist: 'NBkVEws=',
  },
  {
    id: 105,
    title: 'NxAGFhsKBkQfGw==',
    author: 'LRQaAE4qAF4EEBQ=',
    genre: 'NRoZBAAIEA==',
    era: 'NRATAAAIDA==',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '💌⚓💕🌊👩',
    notableQuotes: [
      'PhoBRR4CEF8TEFoXFUVeBBAVSVU9RQ8GVUURGRxaDQJCBRxVRx0VCQhLHUIAEFQ=',
      'Mx0RFwtLFkIFGR5aBARbDkUbAhAaRQAEVVkHGloSCQRfHxZZFBpUCh4OGwM=',
      'KgxUDAoOFA0fE1odAwpJSwYWCgUVCxdLHF5QARIfTAZCBhUYCQxUCghLFkEVAx8IQEVaDgkVShwaAwEZGEgUVQofAxVBDkUODxpUDQ8dEA0RVR0ICQRZSwEcBhlUCghLFkIeAx8IHwRZAgoXSQ==',
      'KBsRRQoEEF5QGxUOTAlCHQBZBlUECQ8IEA0EHR9aAABeGEUfCAdUDQ8dHEMXVQkPCgNIGQAdRxwaRQcfWw==',
    ],
    publicationYear: 'Vk1FUg==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'MBoZBAA=',
  },
  {
    id: 161,
    title: 'NBAaFgtLFEMUVSkfAhZECQwVDgEN',
    author: 'LRQaAE4qAF4EEBQ=',
    genre: 'NRoZBAAIEA==',
    era: 'NRATAAAIDA==',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '👭💔💕🏡📝',
    notableQuotes: [
      'LBsbEk4SGlgCVRUNAkVFChUJDhsRFh1F',
      'Mx0RRQMEB0hQPFoRAgpaSwofRwEcAE4cGl8cEVZaGA1ISwgWFRBULE4KGA0TGhQMBQtODgFZLlUHDQ8HGQ0eEAwfHkVeDgBZBlUZBABLAkUfGFozTAZMBUULAhQYCRdLGUIGEFQ=',
      'LgFUDB1LG0IEVQ0SDRENHABZEx0dCwVLGl9QEx8fAEVZAwQNRxgVDgsYVVgDVQ0SA0VaDkUYFRBaRScfVUQDVQ0SDRENHABZAxpa',
      'LlUDDAIHVU8VVRkbAAgDSyxZEBwYCU4JEA0dHAkOHgBeGEUWAVUZHB0OGUte',
    ],
    publicationYear: 'Vk1FVA==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'MBoZBAA=',
  },
  {
    id: 766,
    title: 'IxQCDApLNkIABR8ICgxIBwE=',
    author: 'JB0VFwIOBg00HBkRCQte',
    genre: 'JRwYARsFEl4CGhcbAg==',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '👦📖✍️💔🎭',
    notableQuotes: [
      'MB0REQYOBw05VQkSDQlBSxEMFRtUChsfVVkfVRgfTBFFDkURAgcbRQENVUAJVRUNAkVBAgMcSVta',
      'JhYXDAoOG1kDVQ0TAAkNBAYaEgdUDABLAUUVVRgfHxEAGQAeEhkVEQsPVUsRGBMWBQBeRQ==',
      'KRACABxLF0hQGB8bAkVEBUUYCQwADQcFEhZQGx8MCRcNCQBZARQYFgtQVUMVAx8ITAdISwYLEhAYSw==',
      'LlUbCwISVUwDHloOA0VPDkUfFRARS04/HUhQFw8OGABfDQkQAgZUBBwOVUsCEB9U',
    ],
    publicationYear: 'Vk1BVQ==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'JRoN',
  },
  {
    id: 145,
    title: 'KhwQAQIOGEwCFhI=',
    author: 'IBAbFwkOVWgcHBUO',
    genre: 'NRAVCQcYAQ0+GgwfAA==',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '👩🔬💔🏘️📚💍',
    notableQuotes: [
      'LgFUDB1LG0gGEAhaGApCSwkYExBUEQFLF0hQAhIbGEVUBBBZChwTDRpLHUwGEFoYCQBDRQ==',
      'MB0VEU4PGg0HEFoWBRNISwMWFVlUDAhLG0IEVQ4VTAhMAABZCxwSAE4HEF4DVR4TCgNECBAVE1USChxLEEwTHVoVGA1IGVo=',
      'NxAbFQIOVUwCEFobAAhCGBFZBhkDBBcYVU8VAQ4fHkVZAwQXRwEcAAcZVUMVHB0SDgpfGEUNDxwaDk4fHUgJVRsICUs=',
      'Mx0RRQkZGloZGx1aCwpCD0UWAVUADQtLAkICGR5aBRYNGwQLExkNRQoOBUgeER8UGEVCBUUMCR0dFhoEB0QTVRsZGBYD',
    ],
    publicationYear: 'Vk1DVA==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'PhoBCwlLAkIdFBQ=',
  },
  {
    id: 6130,
    title: 'Mx0RRScHHEwU',
    author: 'LxoZABw=',
    genre: 'IgUdBk47GkgEBwM=',
    era: 'JBkVFh0CFkwc',
    authorNationality: 'IAcRAAU=',
    emoticons: '⚔️🏛️🐴👑😠',
    notableQuotes: [
      'NBwaAkJLOg0XGh4eCRZeR0UNDxBUBAAMEF9QGhxaLQZFAgkVAgZa',
      'Mx0RFwtLHF5QGxUOBAxDDEUYCxwCAE4GGl8VVRsdAwtEEQAdRwEcBABLGEweWw==',
      'JhsNRQMEGEgeAVoXBQJFH0UbAlUbEBxLGUwDAVRaKRNIGRwNDxwaAk4CBg0dGggfTAdIChANDhMBCU4JEE4RAAkfTBJISwQLAlUQCgEGEEle',
      'LxQAAAgeGQ0EGloXCUVMGEUNDxBUAg8fEF5QGhxaJARJDhZZDgZUEQYKAQ0dFBRaGw1CSw0QAxAHRQEFEA0EHRMUC0VEBUURDgZUDQsKB1lQFBQeTBZdDgQSFFUVCwEfHUgCWw==',
    ],
    publicationYear: 'SkJBVQ==',
    setting: 'IAcRAA0O',
    protagonist: 'MBQGFwcEBw==',
  },
  {
    id: 996,
    title: 'IxoaRT8eHFUfAR8=',
    author: 'KhwTEAsHVUkVVTkfHhNMBREcFA==',
    genre: 'NBQADBwO',
    era: 'NAUVCwcYHQ03GhYeCQsNKgIc',
    authorNationality: 'NAUVCwcYHQ==',
    emoticons: '🐴🏰🌾💫🛡️',
    notableQuotes: [
      'MxwYEQcFEg0RAVoNBQtJBgwVCwZa',
      'Mx0RRRoZAFkYVRcbFUVPDkUKEwcREQ0DEElQARITAkkNCRANRxwARQAOA0gCVRgICQRGGEs=',
      'MxobRQMeFkVQBhsUBRFUSwgYHlUWAE4GFEkeEAkJTOKBsQ0KCx1HGBUBCg4GWVAaHFoNCUFRRQ0IVQcAC0sZRBYQWhsfRUQfRRAUWVQEAA9VQx8BWhsfRUQfRQoPGgEJCksXSFE=',
      'MB0RC04HHEsVVRMOHwBBDUUKAhAZFk4HAEMRARMZQEVaAwpZDBsbEh1LAkUVBx9aAQRJBQAKFFUYDAsYSg==',
    ],
    publicationYear: 'VkNEUA==',
    setting: 'NAUVDAA=',
    protagonist: 'KBkQRQMKGw==',
  },
  {
    id: 1497,
    title: 'Mx0RRTwOBVgSGRMZ',
    author: 'NxkVEQE=',
    genre: 'Nx0dCQEYGl0YDA==',
    era: 'JBkVFh0CFkwc',
    authorNationality: 'IAcRAAU=',
    emoticons: '🏛️💭⚖️🔥👁️⛓️',
    notableQuotes: [
      'Mx0RRQMSAUVQGhxaGA1ISwYYERBa',
      'LQAHEQcIEA0ZG1oOBAANBwwfAlUVCwpLFkIeEQ8ZGEVCDUUNDxBUNhoKAUhQHAlaHApeGAwbCxBUCgAHDA0RBlocBRdeH0UQE1UGAB0CEUgDVRMUTBFFDkURAhQGER1LGktQARIfTAZEHwwDAhsHSw==',
      'Mx0RRQMOFF4FBx9aAwMNCkUUBhtUDB1LAkURAVoSCUVJBAAKRwIdEQZLBUIHEAhU',
      'JRBUDgcFEQFQExUITABbDhcACBsRRRcEAA0dEB8OTAxeSwMQAB0ADAAMVUxQHRsICEVPChENCxBa',
    ],
    publicationYear: 'SkZDUA==',
    setting: 'IAcRAA0O',
    protagonist: 'Nx0dCQEYGl0YEAg=',
  },
  {
    id: 69087,
    title: 'Mx0RRSMeB0kVB1oVCkV/BAIcFVU1BgUZGlQU',
    author: 'JhIVEQYKVW4YBxMJGAxI',
    genre: 'KgwHEQsZDA==',
    era: 'LhsAABwcFF8=',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '🔪🕵️📓🏠😱',
    notableQuotes: [
      'Mx0RRRoZAFkYWVoSAxJIHQALRwATCRdLHENQHA4JCQlLR0UQFFUVCRkKDF5QFg8IBQpYGEUYCRFUBwsKAFkZEw8WTBFCSxYcAh4RFx1LFEsEEAhaBRED',
      'MRAGHE4NEFpQGhxaGRYNChccRwIcBBpLAkhQBh8fAUs=',
      'Mx0RRR0CGF0cEAkOTABVGwkYCRQADAEFVUQDVRsWGwRUGEUNDxBUCAEYAQ0cHBEfABwD',
      'LlUVCE4KVUARG1oNBAoNGxANFFUVC04CGEAVGwkfTBNMBxAcRxoaRRoDEA0AEAgJAwtMB0UNCAAXDUA=',
    ],
    publicationYear: 'VkxGUw==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'IxAAAA0fHFsV',
  },
  {
    id: 21,
    title: 'JhAHCh5MBg02FBgWCRY=',
    author: 'JhAHCh4=',
    genre: 'IRQWCQsY',
    era: 'JBkVFh0CFkwc',
    authorNationality: 'IAcRAAU=',
    emoticons: '🦊🐢🦁🐜📖',
    notableQuotes: [
      'NBkbEk4KG0lQBg4fDQFUSxIQCQZUEQYOVV8RFh9U',
      'JlUWDBwPVUQeVQ4SCUVFCgsdRxwHRRkEB1kYVQ4NA0VEBUUNDxBUBxsYHQM=',
      'KRpUBA0fVUIWVRETAgFDDhYKS1UaCk4GFFkEEAhaBApaSxYUBhkYSU4CBg0VAx8ITBJMGBEcA1s=',
      'JRADBBwOVVkYEFoNAwlLSwwXRwYcAAsbUl5QFhYVGA1EBQJX',
    ],
    publicationYear: 'SkNEVQ==',
    setting: 'IAcRAA0O',
    protagonist: 'JhsdCA8H',
  },
  {
    id: 1998,
    title: 'Mx0BFk44BUIbEFogDRdMHw0MFAEGBA==',
    author: 'IQcdAAoZHE4YVTQTCRFXGAYRAg==',
    genre: 'Nx0dCQEYGl0YDA==',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'IBAGCA8F',
    emoticons: '🏔️🦅💫🔥🧙🐍',
    notableQuotes: [
      'IBoQRQcYVUkVFB5U',
      'MB0VEU4PGkgDVRQVGEVGAgkVRxgRRQMKHkgDVRcfTBZZGQoXABAGSw==',
      'LxBUEgYEVUURBlobTBJFEkUNCFUYDBgOVUsfB1oZDQsNCQAYFVUVCQMEBllQFBQDTA1CHEs=',
      'PhoBRQMeBllQHRsMCUVOAwQWFFUDDBoDHENQDBUPTBFCSwIQERBUBwcZAUVQARVaDUVJCgsaDhsTRR0fFF9e',
    ],
    publicationYear: 'Vk1MVg==',
    setting: 'JhkYAAkEB0QTFBY=',
    protagonist: 'NwcbFQYOAQ==',
  },
  {
    id: 2641,
    title: 'JlUmCgEGVVoZARJaDUV7AgAO',
    author: 'Ils5S04tGl8DAR8I',
    genre: 'NRoZBAAIEA==',
    era: 'IhEDBBwPHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '🏠🌅💕🇮🇹🪟',
    notableQuotes: [
      'MBBUBg8YAQ0RVQkSDQFCHEUWCVUHCgMOAUUZGx1aGw1IGQAPAgdUEgtLBlkRGx5U',
      'KxwSAE4CBg0VFAkDTBFCSwYRFRoaDA0HEAFQFw8OTAdIHAwVAxAGDAAMVVkfVQoIDQZZAgYcSQ==',
      'PhoBRQ0KGw0EBxsUHwhEH0UPDgEVCQcfDAFQDBUPTAZMBQsWE1UAFw8FBkAZAVoWAxNISwofRxkdAwtF',
      'LgFUDB1LBkJQERMcCgxOHgkN4oGzFABFAg4UXgRZWjNMA0QFAVkOAVQBBw0TRBMAFg7igbgRQksQFwMQBhYaChtJUAUfFRwJSEsSEQhVBxULCh4NBB0fWhgXWB8NVw==',
    ],
    publicationYear: 'VkxEXQ==',
    setting: 'LgEVCRc=',
    protagonist: 'PhoBCwlLAkIdFBQ=',
  },
  {
    id: 408,
    title: 'Mx0RRT0EAEEDVRUcTCdBCgYSRzMbCQU=',
    author: 'MFsxSyxFVWkFVTgVBRY=',
    genre: 'IgYHBBcY',
    era: 'IhQGCRdLRx0EHVo5CQtZHhcA',
    authorNationality: 'JhgRFwcIFEM=',
    emoticons: '✊🎵📚🌿💭',
    notableQuotes: [
      'Mx0RRR4ZGk8cEBdaAwMNHw0cRwEDAAAfHEgEHVoZCQtZHhcARxwHRRoDEA0ABxUYAABASwofRwEcAE4IGkEfB1oWBQtIRQ==',
      'IhwADQsZVWwdEAgTDwQNHAwVC1UQAB0fB0IJVRMdAgpfCgsaAlUbF04CEkMfBxsUDwANHAwVC1UQAB0fB0IJVTsXCRdECARX',
      'MxpUBwtLFA0AGhUITAhMBUUQFFUcBBwPWQ0SAA5aGAoNCQBZBlUECgEZVV8RFh9aBQsNCkUVBhsQRQENVUkfGRYbHhYNAhZZEx0RRRgOB1RQFxUOGApASwofRx0VFwoYHUQABlQ=',
      'Mx0RRQ0EBllQGhxaAAxPDhcNHlUdFk4HEF4DVQ4SDQsNHw0cRwUGDA0OVUIWVQgfHBdIGBYQCBta',
    ],
    publicationYear: 'VkxEVg==',
    setting: 'MhsdEQsPVX4EFA4fHw==',
    protagonist: 'MAcdEQsZ',
  },
  {
    id: 16389,
    title: 'Mx0RRSsFFkURGw4fCEVsGxcQCw==',
    author: 'IhkdHw8JEFkYVQwVAkVsGQsQCg==',
    genre: 'NRoZBAAIEA==',
    era: 'LhsAABwcFF8=',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '🌸🏰🇮🇹☀️💐',
    notableQuotes: [
      'Mx0RRR0OFl8VAVoVCkVBAgMcRxwHRQcFVUwABQgfDwxMHwwXAFUdER1LF0EVBgkTAgJeRQ==',
      'IgMRFxdLGEIdEBQOTApLSxERDgZUJB4ZHEFQAhMWAEVPDkUYCxwCAEA=',
      'LhNUHAEeVVoZGRZaDgANAwQJFwxYRQAEF0IUDFoZDQsNGBEWF1UNChtF',
      'KBsRRQYKBg0EGloWBRNISwwXRwEcAE4YAEMDHRMUCUVaAwwVAlUbCwtLFkweWw==',
    ],
    publicationYear: 'VkxGVw==',
    setting: 'LgEVCRc=',
    protagonist: 'MBoZBAA=',
  },
  {
    id: 8492,
    title: 'Mx0RRSUCG0pQHBRaNQBBBwoO',
    author: 'NRoWABwfVXpeVTkSDQhPDhcK',
    genre: 'LxoGFwEZ',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JhgRFwcIFEM=',
    emoticons: '👑💛🎭😱📖',
    notableQuotes: [
      'LxQCAE4SGlhQExUPAgENHw0cRywRCQIEAg0jHB0UUw==',
      'Mx0RRSUCG0pQHBRaNQBBBwoORxgBFhpLG0IEVRgfTAFIGAYLDhcRAUA=',
      'JhkbCwlLAUUVVQkSAxdISxERAlUXCQEeEQ0HFAwfH0VPGQAYDFlUEQYOVVkHHBRaHxBDGEUKDhsfRQwOG0gRARJaGA1ISwkYDBBa',
      'NAEGBAAMEA0ZBloOBAANBQweDwFUEgYOB0hQFxYbDw4NGBEYFQZUFwcYEAM=',
    ],
    publicationYear: 'Vk1NUA==',
    setting: 'MhsdEQsPVX4EFA4fHw==',
    protagonist: 'KRQGFw8fGl8=',
  },
  {
    id: 67979,
    title: 'Mx0RRSwHAEhQNhsJGAlI',
    author: 'K1s5S04mGkMEEhUXCRdU',
    genre: 'NRoZBAAIEA==',
    era: 'LhsAABwcFF8=',
    authorNationality: 'JBQaBAoCFEM=',
    emoticons: '🏰💙💕🌲✨',
    notableQuotes: [
      'LlIYCU4JEA0HHBkRCQENCgsdRxMGDBgEGUIFBloOA0VZAwBZAhsQRQENVUAJVR4bFRYD',
      'IRAVF04CBg0EHR9aAxdEDAwXBhlUFgcFWw==',
      'LhNUHAEeVU4RG1oJBRENAgtZFBwYAAAIEA0HHA4STAQNGwALFBoaRQgEBw0YFBYcTARDSw0WEgdUBAAPVVQVAVoYCUVIBREQFRAYHE4IGkAWGggODQdBDklZHhoBRQ8FEQ0EHRsOTBVIGRYWCVUXBABLF0hQEwgTCQtJGEs=',
      'LlUDBAAfVVkfVR4VTBZCBgANDxwaAk4YBUEVGx4TCEs=',
    ],
    publicationYear: 'VkxGUw==',
    setting: 'JBQaBAoK',
    protagonist: 'MBoZBAA=',
  },
  {
    id: 70875,
    title: 'JgcGChkYGEQEHQ==',
    author: 'NBwaBgIKHF9QOR8NBRY=',
    genre: 'NBoXDA8HVWMfAx8W',
    era: 'LRQOH04qEkg=',
    authorNationality: 'JhgRFwcIFEM=',
    emoticons: '🔬💉🏥📚🧪',
    notableQuotes: [
      'Mx0RRR4eB10fBh9aAwMNCkUMCRwCABwYHFkJVRMJTAtCH0UNCFUEFwEPAE4VVRkVAgNCGQgQFAEHSw==',
      'NBYdAAAIEA0ZBloWAwtIBxxZEBoGDkA=',
      'LxBUEg8YVUxQBh8fBwBfSwofRwEGEBoDBg0RGx5aAgpZSwofRxYbCAgEB1kDWw==',
      'Mx0RRQEFGVRQAhsDTBFCSwIcE1UDChwAVUQDVQ4VTBJCGQ5X',
    ],
    publicationYear: 'VkxGUA==',
    setting: 'MhsdEQsPVX4EFA4fHw==',
    protagonist: 'IxoXEQEZ',
  },
  {
    id: 394,
    title: 'JAcVCwgEB0k=',
    author: 'IhkdHw8JEFkYVT0bHw5IBwk=',
    genre: 'NBoXDA8HVWMfAx8W',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '👵🏡🍵👗💬',
    notableQuotes: [
      'JAcVCwgEB0lQHAlaBQsNGwoKFBAHFgcEGw0fE1oOBAANKggYHRoaFkA=',
      'JlUZBABLHF5QBhVaBQsNHw0cRwIVHE4CGw0EHR9aBApYGABX',
      'MB0VEU4PGkgDVRMOTBZEDAsQAQxUDQEcVVoVVR4ICRZeSw0cFRBUBBpLNl8RGxwVHgES',
      'IhYbCwEGDA0HFAlaDQlaChwKRxAYAAkKG1le',
    ],
    publicationYear: 'Vk1BVA==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'KRQGFw8fGl8=',
  },
  {
    id: 986,
    title: 'KhQHEQsZVUweEVo3DQs=',
    author: 'KxAbRToEGV4EGgM=',
    genre: 'KRoCAAIHFA==',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'NQAHFgcKGw==',
    emoticons: '❄️🐴💰👨‍🌾🌨️',
    notableQuotes: [
      'MB0VEU4CBg0EHR9aAQBMBQwXAFUbA04GDA0cHBwfUw==',
      'MBBUBg8FVUIeGQNaBwtCHEUNDxQARRkOVUYeGg1aAgpZAwwXAFs=',
      'Mx0RRR0FGlpQAhsJTANMBwkQCRJUAxwEGA0EHR9aHw5USxIQEx1UAhwOFFlQExUIDwAD',
      'LxBUAwsHAQ0ZG1oSBRYNGwoaDBAAFk4NGl9QFFoXDRFOA0s=',
    ],
    publicationYear: 'Vk1NUA==',
    setting: 'NQAHFgcK',
    protagonist: 'KhAGBgYKG1k=',
  },
  {
    id: 3600,
    title: 'Mx0RRSsYBkwJBloVCkVgBAsNBhwTCws=',
    author: 'KhwXDQsHVUkVVTcVAhFMAgIXAg==',
    genre: 'IgYHBBcY',
    era: 'NRAaBAcYBkweFh8=',
    authorNationality: 'IQcRCw0D',
    emoticons: '📜✍️💭🏰🍷🪞',
    notableQuotes: [
      'NgARRR0KHF5dHx9FTE16AwQNRxEbRSdLHkMfAkVT',
      'Mx0RRQEFGVRQARITAgINCAALExQdC04CBg0EHRsOTAtCHw0QCRJUDB1LFkgCARsTAks=',
      'LlUFEAEfEA0fARIfHhYNBAsVHlUdC04EB0kVB1oOBAANCQANExAGRRoEVUgIBQgfHxYNBhwKAhkSSw==',
      'Mx0RRQkZEEwEEAhaHARfH0UWAVUADQtLAkICGR5dH0VZGQoMBRkRFk4KB0hQEQ8fTBFCSxQMAgYADAEFBg0fE1odHgRABgQLSQ==',
    ],
    publicationYear: 'VkBMVQ==',
    setting: 'IQcVCw0O',
    protagonist: 'MAcdEQsZ',
  },
  {
    id: 224,
    title: 'JlUkBAcZVUIWVTgWGQANLhwcFA==',
    author: 'Mx0bCA8YVWURBx4D',
    genre: 'NRoZBAAIEA==',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '👀💙💔🏴󠁧󠁢󠁥󠁮󠁧󠁿🌊',
    notableQuotes: [
      'JlUDCgMKGw0HHRVaAApbDhZZAgMRF04YGg0cHA4OAAANAhZZCBMAAABLEl8VFA4fHkVZAwQXRwEcAE4MB0gRAR8JGEVACgtX',
      'MxwZAE4IHUweEh8JTABbDhcAEx0dCwlLEFUTEAoOTBZCBgANDxwaAk4cHFkYHBRaGRYNHA0QBB1UDB1LFEEHFAMJTBZYGRULDgYRAU4JDA0THRsUCwAD',
      'Mx0RRR0ADA0HFAlaDwlIChfiga0VEBkEHAAUTxwMWhkAAEwZ4oGxGAkRVBEGDlVZBxwUEQAMQwxFFgFVFQkCSwFFFVUJDg0XXksWHAIYEQFOHxoNEhBaGBkRDR8NCwgXB0UBDVVCHhBaGAMBVEU=',
      'PhoBEQZLHF5QExUVAAxeA15ZBhsQRR0EVUQDVRYVGgAD',
    ],
    publicationYear: 'Vk1DVg==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'PhoBCwlLAkIdFBQ=',
  },
  {
    id: 1259,
    title: 'MwIRCxoSVXQVFAgJTCRLHwAL',
    author: 'JhkRHQ8FEV8VVT4PAQRe',
    genre: 'JhECAAAfAF8V',
    era: 'NRoZBAAfHE4=',
    authorNationality: 'IQcRCw0D',
    emoticons: '⚔️🤝👑🏇🗡️',
    notableQuotes: [
      'JhkYRQgEBw0fGx9WTApDDkUfCAdUBAIHWw==',
      'Mx0RFwtLHF5QGx8TGA1IGUURBgUEDAAOBl5QGxUITAhEGAALHlUdC04fHUhQAhUIAAEWSxERAgcRRQcYVUIeGQNaGA1ISwYWCgUVFwcYGkNQGhxaAwtISxYNBgERRRkCAUVQFBQVGA1IGUs=',
      'MwcBAE4NB0QVGx4JTARfDkURBgcQRRoEVUsZGx5WTA1MGQEcFVUACk4HEEwGEFZaDQtJSwwUFxoHFgcJGUhQARVaCgpfDAANSQ==',
      'JlUWFw8dEA0dFBRaHhBDGEUYFFUTFwsKAQ0RVQgTHw4NAgtZBRAXCgMCG0pQFFoZAxJMGQFZBgZUBE4IGloRBx5aBQsNCQAaCBgdCwlLFA0SBxsMCUVACgtX',
    ],
    publicationYear: 'Vk1AUA==',
    setting: 'IQcVCw0O',
    protagonist: 'NAIbFwoYGEwe',
  },
  {
    id: 3207,
    title: 'KxACDA8fHUwe',
    author: 'Mx0bCA8YVWUfFxgfHw==',
    genre: 'NxoYDBoCFkwcVSoSBQlCGAoJDww=',
    era: 'IhQGCRdLOEIUEAgU',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '👑📜⚖️🐉🏛️😨',
    notableQuotes: [
      'KxwSAE4CBg0eFAkOFUkNCRcMExwHDUJLFEMUVQkSAxdZRQ==',
      'Mx0RRQ0EG0kZARMVAkVCDUUUBhtUDB1LFA0TGhQeBRFEBAtZCBNUEg8ZVUIWVR8MCRdUBAscRxQTBAcFBllQEAwfHhxCBQBX',
      'LxAYCU4CBg0EBw8OBEVeDgAXRwEbCk4HFFkVWw==',
      'JBoCAAAKG1kDWVoNBRFFBBANRwEcAE4YAkICEVZaDRdISwcME1UDChwPBgM=',
    ],
    publicationYear: 'VkNBVA==',
    setting: 'Mx0RChwOAUQTFBY=',
    protagonist: 'NQAYABw=',
  },
  {
    id: 3296,
    title: 'JBoaAwsYBkQfGwk=',
    author: 'NBQdCxpLNFgXAAkOBQtI',
    genre: 'JgAACgwCGkoCFAoSFQ==',
    era: 'JBkVFh0CFkwc',
    authorNationality: 'NRoZBAA=',
    emoticons: '🙏📖💡✝️👤🍐',
    notableQuotes: [
      'KAAGRQYOFF8EBlobHgANGQAKExkRFh1LAEMEHBZaGA1IEkULAgYARQcFVXQfAFQ=',
      'IAcVCxpLGEhQFhIbHxFEHxxZBhsQRQ0EG1kZGx8UDwABSwcME1UaChpLDEgEWw==',
      'Mx0RRRkEB0EUVRMJTAQNCQoWDFlUBAAPVVkYGgkfTBJFBEUdCFUaChpLAV8RAx8WTBdICgFZCBsYHE4EG0hQBRsdCUs=',
      'KhAaRQkEVUwSBxUbCEVZBEUOCBsQABxLFFlQARIfTA1IAgIREwZUCghLGEIFGw4bBQteR0UYCRFUEQYODA0AFAkJTAdUSxERAhgHAAIdEF5QAhMOBApYH0UOCBsQABwCG0pe',
    ],
    publicationYear: 'VExD',
    setting: 'KRoGEQZLNEsCHBkb',
    protagonist: 'NBQdCxo=',
  },
  {
    id: 3300,
    title: 'Mx0RRTkOFEEEHVoVCkVjChEQCBsH',
    author: 'JhEVCE44GEQEHQ==',
    genre: 'IhYbCwEGHE4D',
    era: 'IhsYDAkDAUgeGB8UGA==',
    authorNationality: 'NBYbERoCBkU=',
    emoticons: '💰📈🏭🤝📊✋',
    notableQuotes: [
      'LgFUDB1LG0IEVRwIAwgNHw0cRxcRCwsdGkEVGxkfTApLSxERAlUWEBoIHUgCVQ4SDRENHABZAg0EAA0fVUIFB1oeBQtDDhdX',
      'Mx0RRQcFA0QDHBgWCUVFCgsdRxoSRRoDEA0dFAgRCRED',
      'KRpUFgEIHEgEDFoZDQsNGBALAhkNRQwOVUscGg8IBRZFAgseRxQaAU4DFF0ADFZaAwMNHA0QBB1UEQYOVUsRB1odHgBMHwALRwUVFxpLGktQARIfTAhIBgccFQZUBBwOVV0fGghaDQtJSwgQFBAGBAwHEAM=',
      'KxQWChsZVVoRBloOBAANDQwLFAFUFRwCFkhcVQ4SCUVCGQweDhsVCU4bAF8THRsJCUhABAscHlUADQ8fVVoRBloKDQxJSwMWFVUVCQJLAUUZGx0JQg==',
    ],
    publicationYear: 'VkJDUw==',
    setting: 'JQcdEQ8CGw==',
    protagonist: 'IhYbCwEGHF4E',
  },
  {
    id: 5827,
    title: 'Mx0RRT4ZGk8cEBcJTApLSzURDhkbFgEbHVQ=',
    author: 'JRAGERwKG0lQJw8JHwBBBw==',
    genre: 'Nx0dCQEYGl0YDA==',
    era: 'IhEDBBwPHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '🤔💭📚🧠❓🪑',
    notableQuotes: [
      'Mx0RRRgKGVgVVRUcTBVFAgkWFBoEDRdLHF5QHBRaBRFeSxMcFQxUEAAIEF8EFBMUGBwD',
      'Nx0dCQEYGl0YDFoTH0VZBEUbAlUHERsPHEgUVRQVGEVLBBdZAxASDAACAUhQFBQJGwBfGEUbEgFUFw8fHUgCVRwVHkVZAwBZFgARFhoCGkMDVQ4SCQheDgkPAgZa',
      'Mx0RFwtLHF5QGA8ZBEVdBwAYFAAGAE4fGg0SEFodDQxDDgFZAQcbCE4eBkgcEAkJTA5DBBIVAhETAEA=',
      'Mx0RRQEJBkgCAx8IQEVaAwAXRx0RRR0OEEADVQ4VTA1EBhYcCxNUEQFLF0hQGhgJCRdbAgseRxRUFhoEG0hcVRMJTBdICgkVHlUbBx0OB1sZGx1aGA1ISwAfARAXER1LGktQARIfTBZZBAscRwAECgBLHUQdBh8WCks=',
    ],
    publicationYear: 'VkxFVw==',
    setting: 'Mx0RChwOAUQTFBY=',
    protagonist: 'Nx0dCQEYGl0YEAg=',
  },
  {
    id: 6593,
    title: 'Mx0RRSYCBlkfBwNaAwMNPwoURz8bCwsYWQ0RVTwVGQtJBwwXAA==',
    author: 'LxAaFxdLM0QVGR4TAgI=',
    genre: 'NxwXBBwOBlwFEA==',
    era: 'IBAbFwkCFEM=',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '👶🏠💕🎭🍺',
    notableQuotes: [
      'LgFUDB1LGFgTHVofDRZEDhdZExpUCA8AEA0XGhUeTAhIBUUODgYRRRoDFENQARVaAQRGDkUbBhFUCAsFVUofGh5U',
      'KxoCAE4KG0lQBhkbAgFMB0UYFRBUEQYOVU8VBg5aHxJIDhEcCRAGFk4EEw0EEBtU',
      'JlUHDAAMGUhQFxseTAROH0UXCFUZChwOVU4fGwkOBRFYHwAKRxRUEwcHGUwZG1oTAkVBAgMcRwEcBABLFA0DHBQdAAANCQQdRwUVFxpLGkNQARIfTBZZCgIcSQ==',
      'IAAdCRpLHUwDVQwfHhwNGhAQBB5UAA8ZBg0EGlobAkVMCAYMFBQADAEFWw==',
    ],
    publicationYear: 'VkJAXA==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'KAcEDQ8F',
  },
  {
    id: 6761,
    title: 'Mx0RRS8PA0geAQ8ICRYNBANZIRAGAQcFFEMUVTkVGQtZSyMYEx0bCA==',
    author: 'MxoWDA8YVX4dGhYWCRFZ',
    genre: 'NBQADBwO',
    era: 'IBAbFwkCFEM=',
    authorNationality: 'NBYbERoCBkU=',
    emoticons: '🎭🗡️💰😈🎪',
    notableQuotes: [
      'JlUfCw8dEA0ZBlobTA5DChMcRxwaRQ8FDA0TGg8UGBdURQ==',
      'KRoADQcFEg0ZBloXAxdISwEcBBAdEQgeGQ0EHRsUTBFFDkUYFwURBBwKG04VVRUcTA1YBgwVDgENSw==',
      'MRwXAE4YHUIFGR5aDQlaChwKRxcRRQsTBUIDEB5aGAoNCAoXExAZFRpHVU8FAVoOBAANHQwLEwAbEB1LGEwJVRkWDQxASwoMFVUVFR4HFFgDEFQ=',
      'Mx0RRRkEB0EUVRMJTAQNHQQKE1UXCgMOEVRQGhxaCRdfBBcKSQ==',
    ],
    publicationYear: 'VkJBVg==',
    setting: 'IgAGCh4O',
    protagonist: 'KhQa',
  },
  {
    id: 11030,
    title: 'LhsXDAoOG1kDVRMUTBFFDkU1DhMRRQENVUxQJhYbGgANLAwLCw==',
    author: 'LxQGFwcOAQ06FBkVDhY=',
    genre: 'JgAACgwCGkoCFAoSFQ==',
    era: 'JhsAAAwOGUEFGA==',
    authorNationality: 'JhgRFwcIFEM=',
    emoticons: '⛓️🏃‍♀️🙏📖✊',
    notableQuotes: [
      'NBkVEwsZDA0ZBloOCRdfAgcVAlUSChxLGEgeTloYGRENAhFZDgZUAw8ZVUAfBx9aGABfGQwbCxBUAwEZVVofGB8UQg==',
      'LlUDBB1LF0ICG1obTBZBChMcXFUWEBpLPA0eEAwfHkVGBQAORxwARRoCGUFQBhMCTBxIChcKRxoSRQYKBV0JVRkSBQlJAwoWA1UcBApLBUwDBh8eTARaChxX',
      'Mx0RFwtLHF5QGxVaHw1MDwoORxoSRQIKAg0EGloKHgpZDgYNRx0RF04NB0IdVRMUHxBBH0lZAQcbCE4dHEIcEBQZCUkNBBdZAgMRC04NB0IdVR4fDRFFRQ==',
      'KgxUCA8YAUgCVRgfCwRDSxEWRwIcDB0bEF9QExUPAEVaBBcdFFUdC04GDA0VFAhU',
    ],
    publicationYear: 'Vk1CVA==',
    setting: 'MhsdEQsPVX4EFA4fHw==',
    protagonist: 'NBkVEws=',
  },
  {
    id: 22381,
    title: 'KgwADR1LFEMUVTYfCwBDDxZZCBNUJAAIHEgeAVo9HgBICABZBhsQRTwEGEg=',
    author: 'Ils5S04pEF8VGwk=',
    genre: 'KgwADQEHGkoJ',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '⚡🏛️🐉🦅🌿',
    notableQuotes: [
      'Mx0RRQkEEV5QAh8ICUVeHhUJCAYRAU4fGg0CEAkfAQdBDkUUCAcABAIYWQ0HHRUXTBFFDhxZARQGRR0eB10RBgkfCEVEBUUbAhQBERdF',
      'LhtUEQYOVU8VEhMUAgxDDEUNDxAGAE4cFF5QNhIbAxYD',
      'Mx0RRQkEEV5QGhxaIwlUBhUMFFUDABwOVU8VGRMfGgBJSxEWRxEDAAIHVUIeVQ4SCUVeHggUDgFUCghLOEIFGw5aIwlUBhUMFFs=',
      'PRABFk4cFF5QARIfTBZYGxccChBUFxsHEF9QGhxaCwpJGEUYCRFUCAsFWw==',
    ],
    publicationYear: 'Vk1MVQ==',
    setting: 'IAcRAA0O',
    protagonist: 'LxAGCg==',
  },
  {
    id: 24869,
    title: 'Mx0RRTwKGEwJFBQb',
    author: 'MRQYCAcAHA==',
    genre: 'IgUdBk47GkgEBwM=',
    era: 'JBkVFh0CFkwc',
    authorNationality: 'LhsQDA8F',
    emoticons: '🏹👑🐒🌺🔥',
    notableQuotes: [
      'Ix0VFwMKVUQDVQ4SCUVPChYQFFUbA04fHUhQABQTGgBfGABX',
      'MwcBEQZLHF5QARIfTA1EDA0cFAFUEwcZAVgVWw==',
      'JlUEABwYGkNQHAlaDgpfBUUYCxoaAE4KG0lQERMfH0VMBwoXAk5UBAAPVUUVVR8CHABfAgAXBBAHRRoDEA0XGhUeTARDD0UbBhFUBgEFBkgBAB8UDwBeSwofRx0dFk4AFF8dFFobAApDDks=',
      'KBsRRR0DGlgcEVoKCRdLBBcURx0dFk4PEEgUBlocAxcNHw0cRxcRCwsNHFlQGhxaAQRDAAwXA1s=',
    ],
    publicationYear: 'SkFEVQ==',
    setting: 'LhsQDA8=',
    protagonist: 'NwcdCw0O',
  },
  {
    id: 27827,
    title: 'Mx0RRSUKGExQJg8OHgQ=',
    author: 'MRQAFhcKDEweFA==',
    genre: 'Nx0dCQEYGl0YDA==',
    era: 'JBkVFh0CFkwc',
    authorNationality: 'LhsQDA8F',
    emoticons: '💕🌸📜🕉️🎭',
    notableQuotes: [
      'NxkRBB0eB0hQHAlaDRYNBQAaAgYHBBwSVUsfB1ofFAxeHwAXBBBUBB1LE0IfEVQ=',
      'JlUZBABLBkUfABYeTAlIChcXRwEcAE4KB1kDVRsUCEVeCAwcCRYRFk4NB0IdVQ4SCUVbDhcARxcRAgcFG0QeElQ=',
      'KxoCAE4MB0IHBloYFUVKAhMQCRJa',
      'JlUDDB0OVUARG1oJBApYBwFZChQGFxdLFA0XHAgWTBJFBEUQFFUaAAcfHUgCVQ4VA0VLCgwLRxsbF04fGkJQERsIB0s=',
    ],
    publicationYear: 'VEVE',
    setting: 'LhsQDA8=',
    protagonist: 'NRAVAQsZ',
  },
  {
    id: 36034,
    title: 'MB0dEQtLO0QXHQ4J',
    author: 'IQwbAQEZVWkfBg4VCRNeABw=',
    genre: 'KRoCAAIHFA==',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'NQAHFgcKGw==',
    emoticons: '🌙💔🚶😢🌃',
    notableQuotes: [
      'KgxUIgEPWQ0RVQ0SAwlISwgQCQAAAE4EEw0SGRMJH0QNIhZZEx0VEU4fGkJQGRMOGAlISwMWFVUVRRkDGkEVVRYTCgBZAggcWA==',
      'LlUVCE4KVUkCEBsXCRcD',
      'JgFUBgsZAUwZG1oXAwhIBREKRzxUAwsOGQ0DGloXGQZFSw0YFwUdCwsYBg0EHRsOTAxZSwMLDhIcEQsFBg0dEFQ=',
      'LlUBFgsPVVkfVQkKCQtJSxIRCBkRRQoKDF5QHBRaARwNGQoWCllUBAAPVU4fABYeTAtCH0UbFRwaAk4GDF4VGRxaGAoNDApZCAAASw==',
    ],
    publicationYear: 'Vk1AXQ==',
    setting: 'NQAHFgcK',
    protagonist: 'IwcRBAMOBw==',
  },
  {
    id: 55264,
    title: 'KBtUIhwEAlkYVRsUCEVrBBcU',
    author: 'I1I1Fw0SVXoVGw4NAxdZA0UtDxoZFR0EGw==',
    genre: 'NBYdAAAIEA==',
    era: 'IhEDBBwPHEwe',
    authorNationality: 'NBYbERoCBkU=',
    emoticons: '🐚🔬📐🌀🦋',
    notableQuotes: [
      'Mx0RRQgEB0BQGhxaDQsNBAcTAhYARQcYVUxQERMbCxdMBkUWAVUSChwIEF5e',
      'JBAYCU4KG0lQARMJHxBIR0UKDxAYCU4KG0lQFxUUCUkNBwAYAVUVCwpLE0EfAh8IQEVMGQBZFBpUCA8FDA0AGggOBQpDGEUWAVUZBBofEF9e',
      'KhQADQsGFFkZFglaBRYNHw0cRwYAEAoSVUIWVRsWAEVdBBYKDhcYAE4cGl8cEQlU',
      'Mx0RRQYKB0AfGwNaAwMNHw0cRwIbFwIPVUQDVRcbCAANBgQXDhMRFhpLHENQMxUIAUVMBQFZKQAZBwsZWw==',
    ],
    publicationYear: 'VkxFUg==',
    setting: 'Mx0RChwOAUQTFBY=',
    protagonist: 'NBYdAAAfHF4E',
  },
  {
    id: 70114,
    title: 'Mx0RRSwCEg02Gg8I',
    author: 'JhIVEQYKVW4YBxMJGAxI',
    genre: 'KgwHEQsZDA==',
    era: 'LhsAABwcFF8=',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '🔍🎩4️⃣😈🌍',
    notableQuotes: [
      'LlUVCE4FGllQGhQfTBFCSxccCwxUEB4EGw0EHR9aCR1dDhcNRxoEDAACGkNe',
      'Mx0RRQICAVkcEFodHgBUSwYcCxkHSU4fHUgJVQkOBQlBSwMMCRYADAEFWw==',
      'Mx0RFwtLFF8VVRwVGRcNBANZEx0RCEJLFEMUVRgfGBJIDgtZEx0RCE4fHUgJVQgPAAANHw0cRwIbFwIPWw==',
      'KhAADQEPWQ0fBx4fHkkNCgsdRxAMBA0fG0gDBlRaOA1IGABZBgcRRRoDEA0EHRMUCxYNHA0QBB1UCA8fAUgCWw==',
    ],
    publicationYear: 'VkxGUg==',
    setting: 'MBoGCQocHEkV',
    protagonist: 'IxAAAA0fHFsV',
  },
  {
    id: 4085,
    title: 'Mx0RRS8PA0geAQ8ICRYNBANZNRoQABwCFkZQJxsUCApA',
    author: 'MxoWDA8YVX4dGhYWCRFZ',
    genre: 'NxwXBBwOBlwFEA==',
    era: 'IBAbFwkCFEM=',
    authorNationality: 'NBYbERoCBkU=',
    emoticons: '⚓🗡️💔🎭🌊',
    notableQuotes: [
      'IRQXER1LFF8VVQkOGQdPBBcXRwEcDAAMBgM=',
      'KhwHAwEZAVgeEAlaAwtISwYYCVURCwoeB0jigaQBEh8VRU4ECBxHEwYKA0saWAQGEx4JSw==',
      'LlUYAAgfVWgeEhYbAgEBSxAXBBAGEQ8CGw0fE1oXFUVLChEcSQ==',
      'IRoGERsFEA0ZBlobTANECA4VAlUTCgoPEF4DWw==',
    ],
    publicationYear: 'VkJAXQ==',
    setting: 'IgAGCh4O',
    protagonist: 'NBQdCQEZ',
  },
  {
    id: 70882,
    title: 'Mx0RRS0HAEhQGhxaGA1ISyscEFUkDAA=',
    author: 'IhETBBxLIkwcGRsZCQ==',
    genre: 'KgwHEQsZDA==',
    era: 'LhsAABwcFF8=',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '📍🔍💀🏠🔐',
    notableQuotes: [
      'Mx0RRQ0HEFsVBx8JGEVOGQwUDhsVCU4HEEwGEAlaDwlYDhZX',
      'KgAGAQsZVVoZGRZaAxBZRQ==',
      'IgMRFxdLGUITHloSDRYNCkUSAgxYRQ8FEQ0VAx8IFUVAEhYNAgcNRQYKBg0RVQkVABBZAgoXSQ==',
      'Mx0RRRoZAFkYVRIbH0VMSxIYHlUbA04IGkAZGx1aGAoNBwweDwFa',
    ],
    publicationYear: 'VkxGVg==',
    setting: 'IhsTCQ8FEQ==',
    protagonist: 'LRoBFwAKGUQDAQ==',
  },
  {
    id: 72133,
    title: 'Mx0RRSEIAUIAAAk=',
    author: 'IQcVCwVLO0ICBxMJ',
    genre: 'KRQAEBwKGUQDGA==',
    era: 'NwcbAhwOBl4ZAx9aKRdM',
    authorNationality: 'JhgRFwcIFEM=',
    emoticons: '🐙🌾🚂💰⚔️',
    notableQuotes: [
      'Mx0RRRkDEEwEVRMJTAJfBBIQCRJa',
      'IRoGBgtLGkMcDFoZDQsNGBAaBBARAU4CGw0EHR9aGwpfBwFX',
      'Mx0RRQkZEEwEVRMIAwsNBgoXFAERF04cHFkYVRMOH0VeAgseCxBUABcOWQ0TDBkWAxVICgtVRwcRAUA=',
      'KhAaRRkOB0hQGxUOBAxDDElZAxAVEQZLAkwDVRQVGA1EBQJVRxkdAwtLAkwDVRQVGA1EBQJX',
    ],
    publicationYear: 'VkxEVA==',
    setting: 'MhsdEQsPVX4EFA4fHw==',
    protagonist: 'IRQGCAsZ',
  },
  {
    id: 70883,
    title: 'IxoXEQEZVWURARIfHgsKGEU9BgATDRoOB14=',
    author: 'KgcHS04jW29eVSobGQlB',
    genre: 'IRwXEQcEGw==',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '👨‍⚕️👩‍👧‍👧🏠💕📖',
    notableQuotes: [
      'JlUTCgEPVUsRGBMWFUVEGEUYRxcYAB0YHEMXVRgfFQpDD0UUAhQHEBwOWw==',
      'Mx0RRQYOFF8EVREUAxJeSxIRBgFUEQYOVUAZGx5aAwNZDgtZARoGAgsfBgM=',
      'LBwaAQAOBl5QHAlaDUVBCgseEhQTAE4cHUQTHVoOBAANDwAYAVUXBABLHUgRB1obAgENHw0cRxcYDAAPVU4RG1oJCQAD',
      'IgMRFxdLHUIdEFoSDRYNAhEKRwYAChwSVVkfVQ4fAAkD',
    ],
    publicationYear: 'Vk1NUA==',
    setting: 'IhsTCQcYHQ0GHBYWDQJI',
    protagonist: 'MBoZBAA=',
  },
  {
    id: 3306,
    title: 'JgFUNhsdGUxQNxsD',
    author: 'LRocC04jFF8XBxsMCQ==',
    genre: 'MBQGRSMOGEIZBw==',
    era: 'MCI9',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '⚔️🏥🌅💀🎖️',
    notableQuotes: [
      'MBQGRQcYVUMfAVobTBVECAsQBFs=',
      'Mx0RRR0fB0gEFhIfHkhPDgQLAgcHRRkEB0YVEVoNBRFFBBANRwcRFhpF',
      'MBBUDQ8PVU4fGB9aGA1fBBAeD1UcAAIHVVkfEh8OBABfRQ==',
      'IgMRFxdLGEweVR4TCEVFAhZZAwAAHE4fHUwEVR4bFUs=',
    ],
    publicationYear: 'VkxFUw==',
    setting: 'MwAGDgsS',
    protagonist: 'NBoYAQcOBw==',
  },
  {
    id: 70236,
    title: 'Mx0RRT0OFl8VAVoVCkVZAwBZKBkQRSMCGUE=',
    author: 'IQcVCwUHHENQIlRaKAxVBAs=',
    genre: 'KgwHEQsZDA==',
    era: 'LhsAABwcFF8=',
    authorNationality: 'JhgRFwcIFEM=',
    emoticons: '🏭🔍👦💵🕵️',
    notableQuotes: [
      'IgMRFxdLGFQDAR8IFUVFChZZBlUHCgIeAUQfG1Q=',
      'Mx0RRSYKB0kJVTgVFRYNBQAPAgdUAgcdEA0FBVQ=',
      'JBkBAB1LFkweVRgfTANCHgsdRxwaRRoDEA0dGgkOTBBDDh0JAhYAAApLBUERFh8JQg==',
      'MxAVCBkEB0ZQGBsRCRYNHw0cRxEGAA8GVVofBxFU',
    ],
    publicationYear: 'VkxGUg==',
    setting: 'MhsdEQsPVX4EFA4fHw==',
    protagonist: 'PhoBCwlLGEwe',
  },
  {
    id: 70302,
    title: 'IhEBBg8fHEIeVRsUCEVZAwBZIBobAU4nHEsV',
    author: 'JRAGERwKG0lQJw8JHwBBBw==',
    genre: 'Nx0dCQEYGl0YDA==',
    era: 'LhsAABwcFF8=',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '📚👶🎓💭🌍',
    notableQuotes: [
      'Mx0RRQkEGklQGRMcCUVEGEUWCRBUDAAYBUQCEB5aDhwNBwoPAlUVCwpLElgZER8eTAdUSw4XCAIYAAoMEAM=',
      'IRAVF04CBg0EHR9aAQREBUUKCAAGBgtLGktQBg8KCRdeHwwNDhoaSw==',
      'Mx0RRQgeG0kRGB8UGARBSwEcARAXEU4EEw0WFA4SCRdeSwwKRwEcBBpLAUUVDFoNDQtZSxERAhwGRQ0DHEEUBx8UTBFCSwccRxRUBhwOEUQEVQ4VTBFFDghX',
      'IhEBBg8fHEIeVQkSAxBBD0UYDhhUBBpLEkQGHBQdTAZFAgkdFRAaRRoDEA0RFxMWBRFUSxEWRwEcDAAAWQ0eGg5aGAoNCgYaAgUARQwOGUQVEwlU',
    ],
    publicationYear: 'VkxGUw==',
    setting: 'Mx0RChwOAUQTFBY=',
    protagonist: 'Nx0dCQEYGl0YEAg=',
  },
  {
    id: 70471,
    title: 'LBQWEAUC',
    author: 'PRrCnUUlAhtOERwe',
    genre: 'JAAYERsZFEFQJg4PCBw=',
    era: 'LhsAABwcFF8=',
    authorNationality: 'JhgRFwcIFEM=',
    emoticons: '🎭🇯🇵👘🎶💃',
    notableQuotes: [
      'LBQWEAUCVUQDVQ4SCUVZAwAYExAGRQENVVkYEFoKCQpdBwBX',
      'IgMRFxdLEkgDAQ8ICUVOChcLDhAHRQ0OG1kFBxMfH0VCDUUUAhQaDAAMWw==',
      'Mx0RRQ8ZAQ0ZBloTAkVZAwBZAxAABAcHBgM=',
      'MwcVAQcfHEIeVRsUCEVEBQsWERQADAEFVUkRGxkfTBFCDAANDxAGRQEFVV4EFB0fQg==',
    ],
    publicationYear: 'VkxGUA==',
    setting: 'LRQEBAA=',
    protagonist: 'JhYAChw=',
  },
  {
    id: 70525,
    title: 'NBQcBBwK',
    author: 'IlswS04mGl8VGQ==',
    genre: 'MwcVEwsH',
    era: 'IhEDBBwPHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '🏜️🐪☀️🌅🧭',
    notableQuotes: [
      'Mx0RRQoOBkgCAVoSDRYNAhEKRxoDC04JEEwFAQNU',
      'NBwYAAAIEA0ZBloOBAANBwQXAAAVAgtLGktQARIfTDZMAwQLBls=',
      'Mx0RRR0KG0kDVQ4fAAkNCkUKExoGHE4EGUkVB1oOBARDSxEQChBa',
      'MhsQABxLAUUVVR8UCAlIGBZZFB4NSU4GFENQExMUCBYNAwwKRxwaFgcMG0QWHBkbAgZIRQ==',
    ],
    publicationYear: 'VkxFVw==',
    setting: 'KRoGEQZLNEsCHBkb',
    protagonist: 'MwcVEwsHEF8=',
  },
  {
    id: 71449,
    title: 'KhATRQENVVkYEFoyCQRZAwAL',
    author: 'JhsaDAtLJgNQJg0bAg==',
    genre: 'NRoZBAAIEA==',
    era: 'IhEDBBwPHEwe',
    authorNationality: 'NBYbERoCBkU=',
    emoticons: '💜🏴󠁧󠁢󠁳󠁣󠁴󠁿💕🌸👩',
    notableQuotes: [
      'Mx0RRQYOFFkYEAhaDglCBAgKRxwaRRoDEA0YEBsIGEs=',
      'KxoCAE4NHEMUBlobTBJMEkUNDwcbEAkDVVkYEFoXAwpfGEs=',
      'NBYbEQIKG0lQBhMUCxYNAgtZCgxUFgEeGQM=',
      'Mx0RRRkCGUlQFx8bGRFUSwofRwEcAE4jHEoYGRsUCBYNCAQXCRoARQwOVVkRGB8eQg==',
    ],
    publicationYear: 'VkxEXQ==',
    setting: 'NBYbERoCBkVQPRMdBAlMBQEK',
    protagonist: 'MBoZBAA=',
  },
  {
    id: 71450,
    title: 'KgxULQsKB1lXBloTAkVZAwBZLxwTDQIKG0kD',
    author: 'JhsaDAtLJgNQJg0bAg==',
    genre: 'NRoZBAAIEA==',
    era: 'IhEDBBwPHEwe',
    authorNationality: 'NBYbERoCBkU=',
    emoticons: '❤️🏔️🏴󠁧󠁢󠁳󠁣󠁴󠁿🎵💕',
    notableQuotes: [
      'LxoZAE4CBg0HHR8ICUVZAwBZDxAVFxpLF0gRAQlaHxFfBAseAgYASw==',
      'Mx0RRQMEAEMEFBMUH0VOCgkVRwEbRRoDGl4VVQ0SA0VBBBMcRwEcAANF',
      'JlUnBgEfAUQDHVoSCQRfH0UXAgMRF04NGl8XEA4JTAxZGEURCBgRCQ8FEQM=',
      'LhtUEQYOVWUZEhIWDQtJGElZAwcRBAMYVVkRHh9aCglEDA0NSQ==',
    ],
    publicationYear: 'VkxFVQ==',
    setting: 'NBYbERoCBkVQPRMdBAlMBQEK',
    protagonist: 'KhQa',
  },
  {
    id: 72123,
    title: 'Mx0RRS8ZFlkZFlotAxdBDw==',
    author: 'JB0VFwIOBg04W1ooDRxI',
    genre: 'NBYdAAAIEA==',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '❄️🐻‍❄️🌊🧊🛷',
    notableQuotes: [
      'Mx0RRS8ZFlkZFloSAwlJGEUUHgYAABwCEF5QDB8OTBFCSwccRxEdFg0EA0gCEB5U',
      'LhYRRQ8FEQ0DGxUNTBZFChUcRxQYCU4HHEsVVRIfHgAD',
      'LhtUEQYCBg0WBxUACQsNHAoLCxFYRR0eB1sZAxsWTAxeSxERAlUbCwISVUERAlQ=',
      'Mx0RRQ8eB0ICFFoeDQtODhZZBhYGCh0YVVkYEFofAgFBDhYKRxsdAgYfWw==',
    ],
    publicationYear: 'Vk1DUw==',
    setting: 'JgcXEQcIVV8VEhMVAhY=',
    protagonist: 'Ig0ECQEZEF8=',
  },
  {
    id: 72132,
    title: 'IxQQARdLP0IVUglaKgxJDwkc',
    author: 'LxQAEQcOVWwCGxUWCEVuBwQLDA==',
    genre: 'IRwXEQcEGw==',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JhgRFwcIFEM=',
    emoticons: '🎻👴👶🎵❤️',
    notableQuotes: [
      'KgAHDA1LBl0VFBEJTBJFDgtZEBoGAR1LE0wZGVQ=',
      'Mx0RRQEHEQ0WHB4eAAANHwAVCwZUFhoEB0QVBloVCkVKDgscFRQADAEFBg0AFAkOQg==',
      'IgMRFxdLAVgeEFoZDRdfAgAKRxRUCAsGGl8JWw==',
      'Mx0GChsMHQ0dEBYVCBwBSwkWERBUDB1LB0gdEBcYCRdID0s=',
    ],
    publicationYear: 'Vk1NVQ==',
    setting: 'NQAGBAJLNEAVBxMZDQ==',
    protagonist: 'KBkQRQMKGw==',
  },
  {
    id: 73340,
    title: 'MBoGEQYSVUIWVTITH0VjCggc',
    author: 'LRAaCwcOVW4YFAoKCQlB',
    genre: 'NRAYDAkCGlgDVTwTDxFEBAs=',
    era: 'MRwXEQEZHEwe',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '✝️📖🙏💒👤',
    notableQuotes: [
      'MxpUBwtLAkICARIDTAxeSxEWRwYRFxgOVUIEHR8IH0s=',
      'IRQdEQZLElgZER8JTBFFDkUREhgWCQtLHUgRBw5U',
      'LhtUFgsZA0QTEFoNCUVLAgsdRxoBF04bAF8AGgkfQg==',
      'Mx0RRQMOFF4FBx9aAwMNHAoLEx1UDB1LHENQGg8ITAFIDgEKSQ==',
    ],
    publicationYear: 'Vk1NUQ==',
    setting: 'IhsTCQcYHQ0GHBYWDQJI',
    protagonist: 'KhQa',
  },
  {
    id: 70473,
    title: 'IxoGDA8F',
    author: 'KRAEDQdLNEMUEAgJAws=',
    genre: 'NRAYDAkCGlgDVTwTDxFEBAs=',
    era: 'NwcbAhwOBl4ZAx9aKRdM',
    authorNationality: 'JhgRFwcIFEM=',
    emoticons: '🏠🌾🙏💒👨‍👩‍👧',
    notableQuotes: [
      'IRQdEQZLFEMUVRwbAQxBEkUYFRBUEQYOVUsfABQeDRFEBAsKRxoSRQ9LEkIfEVoWBQNIRQ==',
      'Mx0RRR0CGF0cEFoWBQNISw0WCxEHRRoDEA0UEB8KCRZZSxELEgEcFkA=',
      'IBoQRRkKAU4YEAlaAxNIGUUNDxoHAE4cHUJQFx8WBQBbDks=',
      'KxoCAE4CBg0EHR9aCxdIChEcFAFUBgEGGEweERcfAhED',
    ],
    publicationYear: 'VkxGVA==',
    setting: 'MhsdEQsPVX4EFA4fHw==',
    protagonist: 'PhoBCwlLGEwe',
  },
  {
    id: 28152,
    title: 'NAIbFwpLFEMUVSofAg==',
    author: 'LRocC04qGUoVBxQVAkViHAAXFA==',
    genre: 'JRwbAhwKBUUJ',
    era: 'IBwYAQsPVWwXEA==',
    authorNationality: 'JhgRFwcIFEM=',
    emoticons: '⚔️✒️🎖️📖🇺🇸',
    notableQuotes: [
      'Mx0RRR4OGw0ZBloXBQJFHwwcFVUADQ8FVVkYEFoJGwpfD0lZBQAARQwEAUVQHRsMCUVZAwAQFVUECQ8IEAM=',
      'NxAGFgsdEF8RGxkfTAxeSxERAlUfABdLAUJQBg8ZDwBeGEUQCVUVCQJLEEMUEBsMAxdeRQ==',
      'LhtUEgEZEV5QAh9aCgxDD0UJCAIRF1VLHENQFBkOBQpDR0UOAlUSDAAPVV0FBwoVHwAD',
      'JlUAFxsOVV4fGR4TCRcNDQweDwEHRRkCAUVQHRUUAxcD',
    ],
    publicationYear: 'Vk1MVA==',
    setting: 'MhsdEQsPVX4EFA4fHw==',
    protagonist: 'NBoYAQcOBw==',
  },
  {
    id: 26,
    title: 'NxQGBAoCBkhQORUJGA==',
    author: 'LRocC04mHEEEGhQ=',
    genre: 'IgUdBk47GkgEBwM=',
    era: 'NRAHEQEZFFkZGhQ=',
    authorNationality: 'JQcdEQcYHQ==',
    emoticons: '😈🍎👼🌳🔥',
    notableQuotes: [
      'JRAAEQsZVVkfVQgfBQJDSwwXRz0RCQJLAUURG1oJCRdbDkUQCVU8AA8dEENe',
      'Mx0RRQMCG0lQHAlaBRFeSwoOCVUECQ8IEAFQFBQeTAxDSwwNFBAYA04IFENQGBsRCUVMSy0cBgMRC04EEw04EBYWQg==',
      'KxoaAk4CBg0EHR9aGwRUSwQXA1UcBBwPWQ0EHRsOTApYH0UWAVU8AAIHVUEVFB4JTBBdSxEWRzkdAgYfWw==',
      'JgIVDgtHVUwCHAkfQEVCGUUbAlUSChxLEFsVB1ocDQlBDgtX',
      'LBsbEgIOEUoVVRwVHgdEDwEcCUpUNhsYBUQTHBUPH0kNGQAYFBoaCQsYBgNQIhIDTBZFBBAVA1UADQsCBw08GggeTABDHRxZEx0RCE4fHUwESg==',
    ],
    publicationYear: 'VkNCUg==',
    setting: 'NxQGBAoCBkg=',
    protagonist: 'KhQa',
  },
] as const;

let _decodedBooks: GutenGuessBook[] | null = null;

/**
 * Get decoded books. Lazily decodes on first access.
 */
export function getGutenGuessBooks(): readonly GutenGuessBook[] {
  if (!_decodedBooks) {
    _decodedBooks = GUTENGUESS_BOOKS_ENCODED.map((book) => ({
      id: book.id,
      title: deobfuscate(book.title),
      author: deobfuscate(book.author),
      genre: deobfuscate(book.genre),
      era: deobfuscate(book.era),
      authorNationality: deobfuscate(book.authorNationality),
      emoticons: book.emoticons,
      notableQuotes: book.notableQuotes.map(deobfuscate),
      publicationYear: Number.parseInt(deobfuscate(book.publicationYear), 10),
      setting: deobfuscate(book.setting),
      protagonist: deobfuscate(book.protagonist),
    }));
  }
  return _decodedBooks;
}

export const GUTENGUESS_BOOK_COUNT = GUTENGUESS_BOOKS_ENCODED.length;
