name: test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: api
        run: |
          cd gutenku-vue
          cp .env.dist .env
          yarn install
          yarn lint
      - name: front
        run: |
          cd gutenku-vue
          cp .env.dist .env
          yarn install
          yarn lint
      #- uses: cypress-io/github-action@v4
      #  with:
      #    build: yarn build
      #    start: yarn start
